;;;; cartan_utils.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'cartan_utils
      'boids_main
      (scheme#list)
      '((pretty-print-decomposition . cartan_utils#pretty-print-decomposition)
        (validate-decomposition . cartan_utils#validate-decomposition)
        (cartan-log-decompose . cartan_utils#cartan-log-decompose)
        (cartan-inverse-lookup . cartan_utils#cartan-inverse-lookup)
        (cartan-step-ratio . cartan_utils#cartan-step-ratio)
        (test-cartan-decomposition . cartan_utils#test-cartan-decomposition))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
