;;;; cartan-utils.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'cartan-utils
      '#f
      (scheme#list)
      '((pretty-print-decomposition . cartan-utils#pretty-print-decomposition)
        (validate-decomposition . cartan-utils#validate-decomposition)
        (cartan-log-decompose . cartan-utils#cartan-log-decompose))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
