;;;; core.machine_constants.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'core.machine_constants
      'machine_constants
      (scheme#list)
      '((machine-epsilon . core.machine_constants#machine-epsilon)
        (default-tolerance . core.machine_constants#default-tolerance)
        (e . core.machine_constants#e)
        (pi . core.machine_constants#pi)
        (approx-equal? . core.machine_constants#approx-equal?)
        (safe-log . core.machine_constants#safe-log)
        (trim-leading-zeros . core.machine_constants#trim-leading-zeros)
        (degree . core.machine_constants#degree)
        (poly-xor . core.machine_constants#poly-xor)
        (poly-shift . core.machine_constants#poly-shift)
        (poly-mul . core.machine_constants#poly-mul)
        (poly-mod . core.machine_constants#poly-mod)
        (int->bits . core.machine_constants#int->bits)
        (bits->int . core.machine_constants#bits->int)
        (hamming-weight . core.machine_constants#hamming-weight))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
