;;;; core.kak_decomposition.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'core.kak_decomposition
      '#f
      (scheme#list)
      '((K-frontier . core.kak_decomposition#K-frontier)
        (K-push . core.kak_decomposition#K-push)
        (K-pop . core.kak_decomposition#K-pop)
        (K-empty? . core.kak_decomposition#K-empty?)
        (K-size . core.kak_decomposition#K-size)
        (K-frontier-adaptive . core.kak_decomposition#K-frontier-adaptive)
        (relax-bound . core.kak_decomposition#relax-bound)
        (graph-neighbors . core.kak_decomposition#graph-neighbors)
        (KAK-apply . core.kak_decomposition#KAK-apply)
        (KAK-apply-golay . core.kak_decomposition#KAK-apply-golay)
        (+INF+ . core.kak_decomposition#+INF+))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
