;;;; cross_validation.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'cross_validation
      'cross_validation
      (scheme#list)
      '((validate-golay-witt-consistency
          .
          cross_validation#validate-golay-witt-consistency)
        (validate-cartan-witt-alignment
          .
          cross_validation#validate-cartan-witt-alignment)
        (validate-gc-topology-witt
          .
          cross_validation#validate-gc-topology-witt)
        (validate-machine-constants-witt
          .
          cross_validation#validate-machine-constants-witt)
        (full-system-validation . cross_validation#full-system-validation)
        (cross-module-consistency-contract
          .
          cross_validation#cross-module-consistency-contract)
        (diagnose-inconsistency . cross_validation#diagnose-inconsistency)
        (suggest-correction . cross_validation#suggest-correction)
        (run-cross-validation-tests
          .
          cross_validation#run-cross-validation-tests))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
