;;;; fmm_on_goppa_grid.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'fmm_on_goppa_grid
      'fmm_on_goppa_grid
      (scheme#list)
      '((demo-cartan-golay . fmm_on_goppa_grid#demo-cartan-golay)
        (cartan-fmm-evaluate-golay
          .
          fmm_on_goppa_grid#cartan-fmm-evaluate-golay)
        (m2l-translation . fmm_on_goppa_grid#m2l-translation)
        (p2m-kernel . fmm_on_goppa_grid#p2m-kernel)
        (calculate-geometric-center
          .
          fmm_on_goppa_grid#calculate-geometric-center)
        (local-parameter . fmm_on_goppa_grid#local-parameter)
        (make-goppa-grid . fmm_on_goppa_grid#make-goppa-grid)
        (print-frontier-info . fmm_on_goppa_grid#print-frontier-info)
        (adaptive-frontier-pop . fmm_on_goppa_grid#adaptive-frontier-pop)
        (adaptive-frontier-push . fmm_on_goppa_grid#adaptive-frontier-push)
        (queue-pop . fmm_on_goppa_grid#queue-pop)
        (queue-push . fmm_on_goppa_grid#queue-push)
        (make-queue . fmm_on_goppa_grid#make-queue)
        (stack-pop . fmm_on_goppa_grid#stack-pop)
        (stack-push . fmm_on_goppa_grid#stack-push)
        (make-stack . fmm_on_goppa_grid#make-stack)
        (nCk . fmm_on_goppa_grid#nCk)
        (fact . fmm_on_goppa_grid#fact)
        (c-inv . fmm_on_goppa_grid#c-inv)
        (c-pow . fmm_on_goppa_grid#c-pow)
        (c-abs . fmm_on_goppa_grid#c-abs)
        (c-div . fmm_on_goppa_grid#c-div)
        (c-mul . fmm_on_goppa_grid#c-mul)
        (c-sub . fmm_on_goppa_grid#c-sub)
        (c-add . fmm_on_goppa_grid#c-add)
        (pi . fmm_on_goppa_grid#pi))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
