;;;; golay_frontier.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'golay_frontier
      'golay24_tests
      (scheme#list)
      '((golay24-generator . golay_frontier#golay24-generator)
        (golay24-parity-check . golay_frontier#golay24-parity-check)
        (encode-golay24 . golay_frontier#encode-golay24)
        (decode-golay24 . golay_frontier#decode-golay24)
        (golay-weight . golay_frontier#golay-weight)
        (make-adaptive-frontier . golay_frontier#make-adaptive-frontier)
        (adaptive-frontier-mode . golay_frontier#adaptive-frontier-mode)
        (adaptive-frontier-tau . golay_frontier#adaptive-frontier-tau)
        (adaptive-frontier-codeword
          .
          golay_frontier#adaptive-frontier-codeword)
        (print-golay-info . golay_frontier#print-golay-info))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
