;;;; golay-frontier.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'golay-frontier
      '#f
      (scheme#list)
      '((golay24-generator . golay-frontier#golay24-generator)
        (golay24-parity-check . golay-frontier#golay24-parity-check)
        (encode-golay24 . golay-frontier#encode-golay24)
        (decode-golay24 . golay-frontier#decode-golay24)
        (golay-weight . golay-frontier#golay-weight)
        (make-adaptive-frontier . golay-frontier#make-adaptive-frontier)
        (adaptive-frontier-push . golay-frontier#adaptive-frontier-push)
        (adaptive-frontier-pop . golay-frontier#adaptive-frontier-pop)
        (adaptive-frontier-mode . golay-frontier#adaptive-frontier-mode)
        (adaptive-frontier-tau . golay-frontier#adaptive-frontier-tau)
        (frontier-mode-from-golay . golay-frontier#frontier-mode-from-golay)
        (print-frontier-info . golay-frontier#print-frontier-info))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
