;;;; golay_frontier.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'golay_frontier
      'cross_validation
      (scheme#list)
      '((golay24-generator . golay_frontier#golay24-generator)
        (golay24-parity-check . golay_frontier#golay24-parity-check)
        (encode-golay24 . golay_frontier#encode-golay24)
        (decode-golay24 . golay_frontier#decode-golay24)
        (golay-weight . golay_frontier#golay-weight)
        (golay-to-galois-height . golay_frontier#golay-to-galois-height)
        (galois-height-class . golay_frontier#galois-height-class)
        (codeword-to-octad . golay_frontier#codeword-to-octad)
        (octad-orbit-representative
          .
          golay_frontier#octad-orbit-representative)
        (make-adaptive-frontier . golay_frontier#make-adaptive-frontier)
        (adaptive-frontier-mode . golay_frontier#adaptive-frontier-mode)
        (adaptive-frontier-tau . golay_frontier#adaptive-frontier-tau)
        (adaptive-frontier-codeword
          .
          golay_frontier#adaptive-frontier-codeword)
        (adaptive-frontier-galois-height
          .
          golay_frontier#adaptive-frontier-galois-height)
        (frontier-mode-from-golay . golay_frontier#frontier-mode-from-golay)
        (frontier-mode-from-galois-height
          .
          golay_frontier#frontier-mode-from-galois-height)
        (adaptive-frontier-push . golay_frontier#adaptive-frontier-push)
        (adaptive-frontier-pop . golay_frontier#adaptive-frontier-pop)
        (frontier-respects-witt-symmetry?
          .
          golay_frontier#frontier-respects-witt-symmetry?)
        (galois-orbit-size . golay_frontier#galois-orbit-size)
        (print-golay-info . golay_frontier#print-golay-info)
        (print-galois-interpretation
          .
          golay_frontier#print-galois-interpretation))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
