;;;; goppa-gc-mock.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'goppa-gc-mock
      '#f
      (scheme#list)
      '((gf-multiply . goppa-gc-mock#gf-multiply)
        (gf-inverse . goppa-gc-mock#gf-inverse)
        (encode-goppa . goppa-gc-mock#encode-goppa)
        (goppa-syndrome . goppa-gc-mock#goppa-syndrome)
        (make-toxic-object-graph . goppa-gc-mock#make-toxic-object-graph)
        (toxic-graph? . goppa-gc-mock#toxic-graph?)
        (toxic-graph-nodes . goppa-gc-mock#toxic-graph-nodes)
        (toxic-graph-edges . goppa-gc-mock#toxic-graph-edges)
        (toxic-graph-toxicity . goppa-gc-mock#toxic-graph-toxicity)
        (goppa-weight-to-gc-pressure
          .
          goppa-gc-mock#goppa-weight-to-gc-pressure)
        (simulate-gc-stress . goppa-gc-mock#simulate-gc-stress)
        (analyze-gc-vulnerability . goppa-gc-mock#analyze-gc-vulnerability)
        (make-multivariate-toxic-graph
          .
          goppa-gc-mock#make-multivariate-toxic-graph)
        (compute-algebraic-immunity
          .
          goppa-gc-mock#compute-algebraic-immunity))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
