;;;; kak-decomposition.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'kak-decomposition
      '#f
      (scheme#list)
      '((K-frontier . kak-decomposition#K-frontier)
        (K-push . kak-decomposition#K-push)
        (K-pop . kak-decomposition#K-pop)
        (K-empty? . kak-decomposition#K-empty?)
        (K-size . kak-decomposition#K-size)
        (K-frontier-adaptive . kak-decomposition#K-frontier-adaptive)
        (relax-bound . kak-decomposition#relax-bound)
        (graph-neighbors . kak-decomposition#graph-neighbors)
        (KAK-apply . kak-decomposition#KAK-apply)
        (KAK-apply-golay . kak-decomposition#KAK-apply-golay)
        (+INF+ . kak-decomposition#+INF+))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
