;;;; kak_quiver_safety.import.scm - GENERATED BY CHICKEN 5.2.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'kak_quiver_safety
      'kak_quiver_safety
      (scheme#list)
      '((analyze-frontier-as-quiver
          .
          kak_quiver_safety#analyze-frontier-as-quiver)
        (classify-quiver-type . kak_quiver_safety#classify-quiver-type)
        (kak-apply-quiver-safe . kak_quiver_safety#kak-apply-quiver-safe)
        (estimate-quiver-speedup . kak_quiver_safety#estimate-quiver-speedup)
        (make-quiver-context . kak_quiver_safety#make-quiver-context)
        (quiver-context-steps . kak_quiver_safety#quiver-context-steps)
        (quiver-context-mode . kak_quiver_safety#quiver-context-mode)
        (bsd-vertex-height-bound . kak_quiver_safety#bsd-vertex-height-bound)
        (bsd-arrow-pauli-phase . kak_quiver_safety#bsd-arrow-pauli-phase)
        (arrow-fv-role . kak_quiver_safety#arrow-fv-role)
        (pauli-conj-weight . kak_quiver_safety#pauli-conj-weight)
        (height->bsd-vertex . kak_quiver_safety#height->bsd-vertex)
        (quiver-banach-adjunction?
          .
          kak_quiver_safety#quiver-banach-adjunction?)
        (discrete-picard-condition?
          .
          kak_quiver_safety#discrete-picard-condition?))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
