;;;; machine-constants.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'machine-constants
      '#f
      (scheme#list)
      '((machine-epsilon . machine-constants#machine-epsilon)
        (default-tolerance . machine-constants#default-tolerance)
        (e . machine-constants#e)
        (pi . machine-constants#pi)
        (approx-equal? . machine-constants#approx-equal?)
        (safe-log . machine-constants#safe-log)
        (trim-leading-zeros . machine-constants#trim-leading-zeros)
        (degree . machine-constants#degree)
        (poly-xor . machine-constants#poly-xor)
        (poly-shift . machine-constants#poly-shift)
        (poly-mul . machine-constants#poly-mul)
        (poly-mod . machine-constants#poly-mod)
        (int->bits . machine-constants#int->bits)
        (bits->int . machine-constants#bits->int)
        (hamming-weight . machine-constants#hamming-weight))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
