;;;; machine_constants.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'machine_constants
      'cross_validation
      (scheme#list)
      '((machine-epsilon . machine_constants#machine-epsilon)
        (default-tolerance . machine_constants#default-tolerance)
        (galois-height-bound . machine_constants#galois-height-bound)
        (e . machine_constants#e)
        (pi . machine_constants#pi)
        (approx-equal? . machine_constants#approx-equal?)
        (safe-log . machine_constants#safe-log)
        (height-within-tolerance? . machine_constants#height-within-tolerance?)
        (trim-leading-zeros . machine_constants#trim-leading-zeros)
        (degree . machine_constants#degree)
        (poly-xor . machine_constants#poly-xor)
        (poly-shift . machine_constants#poly-shift)
        (poly-mul . machine_constants#poly-mul)
        (poly-mod . machine_constants#poly-mod)
        (int->bits . machine_constants#int->bits)
        (bits->int . machine_constants#bits->int)
        (hamming-weight . machine_constants#hamming-weight)
        (galois-height . machine_constants#galois-height)
        (height-discriminant . machine_constants#height-discriminant)
        (height-comparison . machine_constants#height-comparison)
        (octad-height . machine_constants#octad-height)
        (witt-galois-correspondence
          .
          machine_constants#witt-galois-correspondence))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
