;;;; machine_constants.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'machine_constants
      'machine_constants
      (scheme#list)
      '((machine-epsilon . machine_constants#machine-epsilon)
        (default-tolerance . machine_constants#default-tolerance)
        (e . machine_constants#e)
        (pi . machine_constants#pi)
        (approx-equal? . machine_constants#approx-equal?)
        (safe-log . machine_constants#safe-log)
        (trim-leading-zeros . machine_constants#trim-leading-zeros)
        (degree . machine_constants#degree)
        (poly-xor . machine_constants#poly-xor)
        (poly-shift . machine_constants#poly-shift)
        (poly-mul . machine_constants#poly-mul)
        (poly-mod . machine_constants#poly-mod)
        (int->bits . machine_constants#int->bits)
        (bits->int . machine_constants#bits->int)
        (hamming-weight . machine_constants#hamming-weight))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
