;;;; module.fmm.fmm-goppa.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'module.fmm.fmm-goppa
      'fmm_on_goppa_grid
      (scheme#list)
      '((make-goppa-grid . module.fmm.fmm-goppa#make-goppa-grid)
        (local-parameter . module.fmm.fmm-goppa#local-parameter)
        (calculate-geometric-center
          .
          module.fmm.fmm-goppa#calculate-geometric-center)
        (cartan-fmm-evaluate-golay
          .
          module.fmm.fmm-goppa#cartan-fmm-evaluate-golay)
        (demo-cartan-golay . module.fmm.fmm-goppa#demo-cartan-golay))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
