;;;; module.fmm.fmm-goppa.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'module.fmm.fmm-goppa
      'fmm_on_goppa_grid
      (scheme#list)
      '((demo-cartan-golay . module.fmm.fmm-goppa#demo-cartan-golay)
        (cartan-fmm-evaluate-golay
          .
          module.fmm.fmm-goppa#cartan-fmm-evaluate-golay)
        (m2l-translation . module.fmm.fmm-goppa#m2l-translation)
        (p2m-kernel . module.fmm.fmm-goppa#p2m-kernel)
        (calculate-geometric-center
          .
          module.fmm.fmm-goppa#calculate-geometric-center)
        (local-parameter . module.fmm.fmm-goppa#local-parameter)
        (make-goppa-grid . module.fmm.fmm-goppa#make-goppa-grid)
        (print-frontier-info . module.fmm.fmm-goppa#print-frontier-info)
        (adaptive-frontier-pop . module.fmm.fmm-goppa#adaptive-frontier-pop)
        (adaptive-frontier-push . module.fmm.fmm-goppa#adaptive-frontier-push)
        (queue-pop . module.fmm.fmm-goppa#queue-pop)
        (queue-push . module.fmm.fmm-goppa#queue-push)
        (make-queue . module.fmm.fmm-goppa#make-queue)
        (stack-pop . module.fmm.fmm-goppa#stack-pop)
        (stack-push . module.fmm.fmm-goppa#stack-push)
        (make-stack . module.fmm.fmm-goppa#make-stack)
        (nCk . module.fmm.fmm-goppa#nCk)
        (fact . module.fmm.fmm-goppa#fact)
        (c-inv . module.fmm.fmm-goppa#c-inv)
        (c-pow . module.fmm.fmm-goppa#c-pow)
        (c-abs . module.fmm.fmm-goppa#c-abs)
        (c-div . module.fmm.fmm-goppa#c-div)
        (c-mul . module.fmm.fmm-goppa#c-mul)
        (c-sub . module.fmm.fmm-goppa#c-sub)
        (c-add . module.fmm.fmm-goppa#c-add)
        (pi . module.fmm.fmm-goppa#pi))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
