;;;; srfi-69.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'srfi-69
      'srfi-69
      (scheme#list)
      '((make-hash-table . srfi-69#make-hash-table)
        (hash-table-ref/default . srfi-69#hash-table-ref/default)
        (hash-table-set! . srfi-69#hash-table-set!)
        (hash-table-walk . srfi-69#hash-table-walk))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
