;;;; srfi-9.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'srfi-9
      'srfi-9
      (scheme#list)
      '()
      (scheme#list)
      (scheme#list))))

;; END OF FILE
