;;;; srfi-1.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'srfi-1
      'srfi-1
      (scheme#list)
      '((fold . srfi-1#fold)
        (filter . srfi-1#filter)
        (filter-map . srfi-1#filter-map))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
