;;;; sssp_tests.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'sssp_tests
      'sssp_tests
      (scheme#list)
      '((test-count . sssp_tests#test-count)
        (test-passed . sssp_tests#test-passed)
        (test-failed . sssp_tests#test-failed)
        (assert-equal . sssp_tests#assert-equal)
        (assert-true . sssp_tests#assert-true))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
