;;;; topological-gc.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'topological-gc
      'topological-gc
      (scheme#list)
      '((make-topological-frontier . topological-gc#make-topological-frontier)
        (topological-gc-collect . topological-gc#topological-gc-collect)
        (topological-gc-stats . topological-gc#topological-gc-stats)
        (set-gc-strategy! . topological-gc#set-gc-strategy!)
        (set-bottleneck-threshold! . topological-gc#set-bottleneck-threshold!)
        (estimate-heap-topology . topological-gc#estimate-heap-topology)
        (report-gc-regions . topological-gc#report-gc-regions)
        (report-connectivity . topological-gc#report-connectivity))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
