;;;; witt_symmetry_explicit.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'witt_symmetry_explicit
      'witt-validator-main
      (scheme#list)
      '((golay-encodes-witt-octad
          .
          witt_symmetry_explicit#golay-encodes-witt-octad)
        (tau-to-octad-size . witt_symmetry_explicit#tau-to-octad-size)
        (octad-level-from-tau . witt_symmetry_explicit#octad-level-from-tau)
        (verify-frontier-preserves-witt
          .
          witt_symmetry_explicit#verify-frontier-preserves-witt)
        (verify-cartan-respects-octads
          .
          witt_symmetry_explicit#verify-cartan-respects-octads)
        (verify-topological-gc-uses-witt
          .
          witt_symmetry_explicit#verify-topological-gc-uses-witt)
        (test-witt-implicit-structure
          .
          witt_symmetry_explicit#test-witt-implicit-structure))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
