;;;; witt_foundation.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'witt_foundation
      'cross_validation
      (scheme#list)
      '((make-witt-context . witt_foundation#make-witt-context)
        (witt-context? . witt_foundation#witt-context?)
        (octad-from-points . witt_foundation#octad-from-points)
        (points-from-octad . witt_foundation#points-from-octad)
        (octad-complement . witt_foundation#octad-complement)
        (octad-intersection . witt_foundation#octad-intersection)
        (octad-weight . witt_foundation#octad-weight)
        (octad-class . witt_foundation#octad-class)
        (witt-automorphism . witt_foundation#witt-automorphism)
        (witt-apply-automorphism . witt_foundation#witt-apply-automorphism)
        (witt-generators-m24 . witt_foundation#witt-generators-m24)
        (witt-orbit . witt_foundation#witt-orbit)
        (witt-cartan-levels . witt_foundation#witt-cartan-levels)
        (octad-at-level . witt_foundation#octad-at-level)
        (level-preserving-partition
          .
          witt_foundation#level-preserving-partition)
        (graph-respects-witt? . witt_foundation#graph-respects-witt?)
        (kak-preserves-witt? . witt_foundation#kak-preserves-witt?)
        (gc-respects-witt-topology?
          .
          witt_foundation#gc-respects-witt-topology?)
        (validate-witt-structure . witt_foundation#validate-witt-structure))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
