-- CayleyDicksonQuiver.AbelianCurse.PeriodPolynomial
--
-- Restricted even period polynomials (Sakugawa, arXiv:2402.13406,
-- Definition 4.1, after Brown [5, Definition 7.1]): homogeneous
-- polynomials f(x,y) of even degree satisfying
--   (4.2) f(x,0) = 0
--   (4.3) f(±x,±y) = f(x,y)
--   (4.4) f(x,y) + f(y,x) = 0
--   (4.5) f(x,y) + f(x-y,x) + f(-y,x-y) = 0
--
-- Not imported by `Everything`; may contain holes.
module CayleyDicksonQuiver.AbelianCurse.PeriodPolynomial where

open import Data.Bool using (Bool; false; true; _∧_)
open import Data.Integer using (ℤ; -_) renaming (+_ to pos; _+_ to _+ℤ_; _*_ to _*ℤ_)
open import Data.List using (List; []; _∷_; map)
open import Data.Nat using (ℕ; zero; suc; _≡ᵇ_; _+_)
open import Data.Nat.Properties using ()
open import Data.Product using (_×_; _,_)
open import Relation.Binary.PropositionalEquality using (_≡_; refl)

------------------------------------------------------------------------
-- Bivariate polynomials
------------------------------------------------------------------------
-- A monomial is a pair of exponents of x and y. A `BiPoly` is a formal
-- integer-linear combination of monomials, represented as before.

Monomial : Set
Monomial = ℕ × ℕ

BiPoly : Set
BiPoly = List (Monomial × ℤ)

mono-eq : Monomial → Monomial → Bool
mono-eq (p , q) (p' , q') = (p ≡ᵇ p') ∧ (q ≡ᵇ q')

is-zero : ℤ → Bool
is-zero (pos zero)    = true
is-zero (pos (suc _)) = false
is-zero _             = false

bp-add-term : Monomial → ℤ → BiPoly → BiPoly
bp-add-term m c []              with is-zero c
... | true  = []
... | false = (m , c) ∷ []
bp-add-term m c ((n , d) ∷ xs)  with mono-eq m n
... | true  with is-zero (c +ℤ d)
...   | true  = xs
...   | false = (n , c +ℤ d) ∷ xs
bp-add-term m c ((n , d) ∷ xs)  | false = (n , d) ∷ bp-add-term m c xs

bp-add-sum : BiPoly → BiPoly → BiPoly
bp-add-sum xs []              = xs
bp-add-sum xs ((m , c) ∷ ys)  = bp-add-sum (bp-add-term m c xs) ys

bp-scale : ℤ → BiPoly → BiPoly
bp-scale c []              = []
bp-scale c ((m , d) ∷ xs) with is-zero (c *ℤ d)
... | true  = bp-scale c xs
... | false = (m , c *ℤ d) ∷ bp-scale c xs

bp-mono-mul : Monomial → ℤ → BiPoly → BiPoly
bp-mono-mul (p , q) c []                    = []
bp-mono-mul (p , q) c (((p' , q') , d) ∷ ys) =
  bp-add-term (p + p' , q + q') (c *ℤ d) (bp-mono-mul (p , q) c ys)

bp-mul : BiPoly → BiPoly → BiPoly
bp-mul []             ys = []
bp-mul ((m , c) ∷ xs) ys = bp-add-sum (bp-mono-mul m c ys) (bp-mul xs ys)

unit-poly : BiPoly
unit-poly = ((zero , zero) , pos 1) ∷ []

bp-pow : ℕ → BiPoly → BiPoly
bp-pow zero    p = unit-poly
bp-pow (suc n) p = bp-mul p (bp-pow n p)

-- Substitutes `u` for `x` and `v` for `y` in the homogeneous
-- polynomial `f`.

compose : BiPoly → BiPoly → BiPoly → BiPoly
compose []               u v = []
compose (((p , q) , c) ∷ f) u v =
  bp-add-sum (bp-scale c (bp-mul (bp-pow p u) (bp-pow q v))) (compose f u v)

X Y XmY negY : BiPoly
X    = ((1 , 0) , pos 1) ∷ []
Y    = ((0 , 1) , pos 1) ∷ []
XmY  = ((1 , 0) , pos 1) ∷ ((0 , 1) , - pos 1) ∷ []
negY = ((0 , 1) , - pos 1) ∷ []

-- Equation (4.5).

three-term : BiPoly → BiPoly
three-term f = bp-add-sum (bp-add-sum f (compose f XmY X)) (compose f negY XmY)

-- Equation (4.4): swapping the two exponents of every monomial.

swap-poly : BiPoly → BiPoly
swap-poly = map (λ ((p , q) , c) → (q , p) , c)

-- Equation (4.3): every monomial has both exponents even.

is-even : ℕ → Bool
is-even zero          = true
is-even (suc zero)    = false
is-even (suc (suc n)) = is-even n

even-mono : Monomial → Bool
even-mono (p , q) = is-even p ∧ is-even q

all-even : BiPoly → Bool
all-even []             = true
all-even ((m , c) ∷ xs) = even-mono m ∧ all-even xs

-- Equation (4.2): every monomial has both exponents positive, so
-- setting y (or x) to zero kills every term.

positive-mono : Monomial → Bool
positive-mono (zero  , _)    = false
positive-mono (_     , zero) = false
positive-mono (suc _ , suc _) = true

all-positive : BiPoly → Bool
all-positive []             = true
all-positive ((m , c) ∷ xs) = positive-mono m ∧ all-positive xs

------------------------------------------------------------------------
-- The generators x^(2i)y^(2j) - y^(2i)x^(2j)
------------------------------------------------------------------------

basis-poly : ℕ → ℕ → BiPoly
basis-poly i j = ((i + i , j + j) , pos 1) ∷ ((j + j , i + i) , - pos 1) ∷ []

------------------------------------------------------------------------
-- The weight-12 (m = 5) restricted even period polynomial
------------------------------------------------------------------------
-- The unique (up to scalar) relation at weight 12 is generated by
-- `x^2y^8 - y^2x^8 - 3(x^4y^6 - y^4x^6)`, matching the coefficients
-- (1, -3) found among the canonical generators.

weight-12-period-poly : BiPoly
weight-12-period-poly = bp-add-sum (basis-poly 1 4) (bp-scale (- pos 3) (basis-poly 2 3))

positive-4-2 : all-positive weight-12-period-poly ≡ true
positive-4-2 = refl

even-4-3 : all-even weight-12-period-poly ≡ true
even-4-3 = refl

antisymmetric-4-4 : bp-add-sum weight-12-period-poly (swap-poly weight-12-period-poly) ≡ []
antisymmetric-4-4 = refl

three-term-vanishes-4-5 : three-term weight-12-period-poly ≡ []
three-term-vanishes-4-5 = refl
