;;;; core/golay_frontier.import.scm - GENERATED BY CHICKEN 5.4.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'core/golay_frontier
      '#f
      (scheme#list)
      '((golay24-generator . core/golay_frontier#golay24-generator)
        (golay24-parity-check . core/golay_frontier#golay24-parity-check)
        (encode-golay24 . core/golay_frontier#encode-golay24)
        (decode-golay24 . core/golay_frontier#decode-golay24)
        (golay-weight . core/golay_frontier#golay-weight)
        (make-adaptive-frontier . core/golay_frontier#make-adaptive-frontier)
        (adaptive-frontier-push . core/golay_frontier#adaptive-frontier-push)
        (adaptive-frontier-pop . core/golay_frontier#adaptive-frontier-pop)
        (adaptive-frontier-mode . core/golay_frontier#adaptive-frontier-mode)
        (adaptive-frontier-tau . core/golay_frontier#adaptive-frontier-tau)
        (frontier-mode-from-golay
          .
          core/golay_frontier#frontier-mode-from-golay)
        (print-frontier-info . core/golay_frontier#print-frontier-info))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
