/-
Copyright (c) 2026 HatsuYakitori. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yoshihiro Hasegawa
-/

import HatsuYakitori.MachineConstants
import Mathlib.Data.Complex.Basic

namespace HatsuYakitori.Fmm

open HatsuYakitori.MachineConstants

/-!
# Golay-driven FMM State Model

This module replaces the autogenerated `FMM.lean` stub with a proof-friendly
state model for the runtime evaluator in
`modules/fmm/fmm_on_goppa_grid.scm`.

The goal of this first pass is intentionally narrow:

1. define the basic carriers used by a Golay-driven FMM evaluation,
2. expose the frontier mode as derived data from `GolayWeight`,
3. state well-formedness predicates for inputs and evaluation states,
4. provide the initial state from which later transition lemmas can start.

This follows the same style as `HopfStructure.lean`: set up small algebraic
containers and derived invariants before proving stronger algorithmic facts.
-/

/-- Points on the Goppa grid are represented by complex coordinates. -/
abbrev GoppaPoint := ℂ

/-- Accumulated FMM potential. -/
abbrev Potential := ℂ

/-- Frontier discipline chosen from the Golay-controlled entropy class. -/
inductive FrontierMode where
  | stack
  | queue
  deriving DecidableEq, Repr

/-- Runtime cells are currently represented by source indices only.
    This mirrors the Scheme hierarchy, where each level stores one list of indices. -/
structure FmmCell where
  sourceIndices : List ℕ

/-- The hierarchy processed by the evaluator, ordered by traversal level. -/
abbrev FmmHierarchy := List FmmCell

/-- Static configuration data for one FMM evaluation. -/
structure FmmConfig where
  order : ℕ
  admissibilityRadius : ℝ := 0.5
  golayWeight : GolayWeight := .w0

/-- A minimal positivity predicate for configuration parameters. -/
def FmmConfig.WellFormed (cfg : FmmConfig) : Prop :=
  0 < cfg.order ∧ 0 < cfg.admissibilityRadius

/-- The discrete Golay class seen by the runtime as a Hamming weight. -/
def FmmConfig.tau (cfg : FmmConfig) : ℕ :=
  cfg.golayWeight.toNat

/-- The corresponding logarithmic height used elsewhere in the Lean development. -/
noncomputable def FmmConfig.galoisHeight (cfg : FmmConfig) : ℝ :=
  HatsuYakitori.MachineConstants.galoisHeight cfg.tau

/-- Low Golay weight uses stack/DFS; dodecad-and-above uses queue/BFS.
    This matches the runtime split at `τ = 12`. -/
def FrontierMode.ofTau (tau : ℕ) : FrontierMode :=
  if tau < 12 then .stack else .queue

/-- Frontier mode derived from the Golay weight class. -/
def FrontierMode.ofGolayWeight (w : GolayWeight) : FrontierMode :=
  FrontierMode.ofTau w.toNat

/-- The frontier mode selected by the configuration. -/
def FmmConfig.frontierMode (cfg : FmmConfig) : FrontierMode :=
  FrontierMode.ofGolayWeight cfg.golayWeight

/-- All external data required to run one FMM evaluation. -/
structure FmmInput where
  grid : List GoppaPoint
  hierarchy : FmmHierarchy
  sources : List ℕ := []
  charges : List Potential
  targetIdx : ℕ
  config : FmmConfig

/-- Input-level well-formedness, kept intentionally lightweight for the first pass. -/
def FmmInput.WellFormed (input : FmmInput) : Prop :=
  input.config.WellFormed ∧
  input.targetIdx < input.grid.length ∧
  input.charges.length = input.grid.length ∧
  (∀ idx ∈ input.sources, idx < input.grid.length) ∧
  (∀ cell ∈ input.hierarchy, ∀ idx ∈ cell.sourceIndices, idx < input.grid.length)

/-- The target point being evaluated. Defaults to `0` outside the well-formed regime. -/
noncomputable def FmmInput.targetPos (input : FmmInput) : GoppaPoint :=
  input.grid.getD input.targetIdx 0

/-- Geometric center of a cell, computed as the average of its indexed grid points. -/
noncomputable def FmmInput.cellCenter (input : FmmInput) (cell : FmmCell) : GoppaPoint :=
  match cell.sourceIndices with
  | [] => 0
  | _ =>
      let sum := cell.sourceIndices.foldl (fun acc idx => acc + input.grid.getD idx 0) 0
      sum / (cell.sourceIndices.length : ℂ)

/-- Near-field predicate matching the current runtime cutoff style. -/
noncomputable def FmmInput.isNearField (input : FmmInput) (cell : FmmCell) : Prop :=
  ‖input.targetPos - input.cellCenter cell‖ < input.config.admissibilityRadius

/-- Mutable portion of the evaluator state.
    `pendingLevels` models the frontier payload, while `frontierMode` and
    `golayWeight` are frozen copies of the configuration for preservation lemmas. -/
structure FmmEvalState where
  pendingLevels : List ℕ
  currentLevel? : Option ℕ := none
  totalPotential : Potential := 0
  frontierMode : FrontierMode
  golayWeight : GolayWeight

/-- State-level invariants needed before any step relation is introduced. -/
def FmmEvalState.WellFormed (input : FmmInput) (state : FmmEvalState) : Prop :=
  state.frontierMode = input.config.frontierMode ∧
  state.golayWeight = input.config.golayWeight ∧
  (∀ level ∈ state.pendingLevels, level < input.hierarchy.length) ∧
  ∀ level, state.currentLevel? = some level → level < input.hierarchy.length

/-- Initial state: every hierarchy level is pending, and no potential has been accumulated. -/
def initialState (input : FmmInput) : FmmEvalState :=
  { pendingLevels := List.range input.hierarchy.length
    frontierMode := input.config.frontierMode
    golayWeight := input.config.golayWeight }

@[simp]
theorem initialState_frontierMode (input : FmmInput) :
    (initialState input).frontierMode = input.config.frontierMode := by
  rfl

@[simp]
theorem initialState_golayWeight (input : FmmInput) :
    (initialState input).golayWeight = input.config.golayWeight := by
  rfl

@[simp]
theorem mem_initialState_pendingLevels (input : FmmInput) (level : ℕ) :
    level ∈ (initialState input).pendingLevels ↔ level < input.hierarchy.length := by
  simp [initialState]

theorem initialState_wellFormed (input : FmmInput) :
    FmmEvalState.WellFormed input (initialState input) := by
  constructor
  · rfl
  constructor
  · rfl
  constructor
  · intro level hlevel
    simpa [initialState] using List.mem_range.mp hlevel
  · intro level hlevel
    simp [initialState] at hlevel

end HatsuYakitori.Fmm
