/-
Copyright (c) 2026 HatsuYakitori. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yoshihiro Hasegawa
-/

import HatsuYakitori.MachineConstants
import Mathlib.Data.Complex.Basic

namespace HatsuYakitori.Fmm

open HatsuYakitori.MachineConstants

/-!
# Golay-driven FMM State Model

This module replaces the autogenerated `FMM.lean` stub with a proof-friendly
state model for the runtime evaluator in
`modules/fmm/fmm_on_goppa_grid.scm`.

The goal of this first pass is intentionally narrow:

1. define the basic carriers used by a Golay-driven FMM evaluation,
2. expose the frontier mode as derived data from `GolayWeight`,
3. state well-formedness predicates for inputs and evaluation states,
4. provide the initial state from which later transition lemmas can start.

This follows the same style as `HopfStructure.lean`: set up small algebraic
containers and derived invariants before proving stronger algorithmic facts.
-/

/-- Points on the Goppa grid are represented by complex coordinates. -/
abbrev GoppaPoint := ℂ

/-- Accumulated FMM potential. -/
abbrev Potential := ℂ

/-- Frontier discipline chosen from the Golay-controlled entropy class. -/
inductive FrontierMode where
  | stack
  | queue
  deriving DecidableEq, Repr

/-- Runtime cells are currently represented by source indices only.
    This mirrors the Scheme hierarchy, where each level stores one list of indices. -/
structure FmmCell where
  sourceIndices : List ℕ

/-- The hierarchy processed by the evaluator, ordered by traversal level. -/
abbrev FmmHierarchy := List FmmCell

/-- Static configuration data for one FMM evaluation. -/
structure FmmConfig where
  order : ℕ
  admissibilityRadius : ℝ := 0.5
  golayWeight : GolayWeight := .w0

/-- A minimal positivity predicate for configuration parameters. -/
def FmmConfig.WellFormed (cfg : FmmConfig) : Prop :=
  0 < cfg.order ∧ 0 < cfg.admissibilityRadius

/-- The discrete Golay class seen by the runtime as a Hamming weight. -/
def FmmConfig.tau (cfg : FmmConfig) : ℕ :=
  cfg.golayWeight.toNat

/-- The corresponding logarithmic height used elsewhere in the Lean development. -/
noncomputable def FmmConfig.galoisHeight (cfg : FmmConfig) : ℝ :=
  HatsuYakitori.MachineConstants.galoisHeight cfg.tau

/-- Low Golay weight uses stack/DFS; dodecad-and-above uses queue/BFS.
    This matches the runtime split at `τ = 12`. -/
def FrontierMode.ofTau (tau : ℕ) : FrontierMode :=
  if tau < 12 then .stack else .queue

/-- Frontier mode derived from the Golay weight class. -/
def FrontierMode.ofGolayWeight (w : GolayWeight) : FrontierMode :=
  FrontierMode.ofTau w.toNat

/-- The frontier mode selected by the configuration. -/
def FmmConfig.frontierMode (cfg : FmmConfig) : FrontierMode :=
  FrontierMode.ofGolayWeight cfg.golayWeight

/-- All external data required to run one FMM evaluation. -/
structure FmmInput where
  grid : List GoppaPoint
  hierarchy : FmmHierarchy
  sources : List ℕ := []
  charges : List Potential
  targetIdx : ℕ
  config : FmmConfig

/-- Input-level well-formedness, kept intentionally lightweight for the first pass. -/
def FmmInput.WellFormed (input : FmmInput) : Prop :=
  input.config.WellFormed ∧
  input.targetIdx < input.grid.length ∧
  input.charges.length = input.grid.length ∧
  (∀ idx ∈ input.sources, idx < input.grid.length) ∧
  (∀ cell ∈ input.hierarchy, ∀ idx ∈ cell.sourceIndices, idx < input.grid.length)

/-- The target point being evaluated. Defaults to `0` outside the well-formed regime. -/
noncomputable def FmmInput.targetPos (input : FmmInput) : GoppaPoint :=
  input.grid.getD input.targetIdx 0

/-- Geometric center of a cell, computed as the average of its indexed grid points. -/
noncomputable def FmmInput.cellCenter (input : FmmInput) (cell : FmmCell) : GoppaPoint :=
  match cell.sourceIndices with
  | [] => 0
  | _ =>
      let sum := cell.sourceIndices.foldl (fun acc idx => acc + input.grid.getD idx 0) 0
      sum / (cell.sourceIndices.length : ℂ)

/-- Distance from the target point to a cell center. -/
noncomputable def FmmInput.cellDistance (input : FmmInput) (cell : FmmCell) : ℝ :=
  ‖input.targetPos - input.cellCenter cell‖

@[simp]
theorem cellDistance_nonneg (input : FmmInput) (cell : FmmCell) :
    0 ≤ input.cellDistance cell := by
  simp [FmmInput.cellDistance]

/-- Near-field predicate matching the current runtime cutoff style. -/
noncomputable def FmmInput.isNearField (input : FmmInput) (cell : FmmCell) : Prop :=
  input.cellDistance cell < input.config.admissibilityRadius

/-- Classification of one interaction cell in the current FMM step. -/
inductive InteractionKind where
  | nearField
  | farField
  deriving DecidableEq, Repr

/-- Runtime branch selected from the geometric near/far classification. -/
inductive KernelBranch where
  | directSum
  | multipole
  deriving DecidableEq, Repr

/-- Convert the geometric cutoff predicate into an explicit runtime tag. -/
noncomputable def FmmInput.interactionKind (input : FmmInput) (cell : FmmCell) : InteractionKind := by
  classical
  exact if input.isNearField cell then .nearField else .farField

@[simp]
theorem interactionKind_eq_nearField_iff (input : FmmInput) (cell : FmmCell) :
    input.interactionKind cell = .nearField ↔ input.isNearField cell := by
  classical
  simp [FmmInput.interactionKind]

@[simp]
theorem interactionKind_eq_farField_iff (input : FmmInput) (cell : FmmCell) :
    input.interactionKind cell = .farField ↔ ¬ input.isNearField cell := by
  classical
  simp [FmmInput.interactionKind]

/-- Near-field cells run the direct summation branch; far-field cells run the multipole branch. -/
def InteractionKind.toKernelBranch : InteractionKind → KernelBranch
  | .nearField => .directSum
  | .farField => .multipole

@[simp]
theorem toKernelBranch_nearField :
    InteractionKind.toKernelBranch .nearField = .directSum := by
  rfl

@[simp]
theorem toKernelBranch_farField :
    InteractionKind.toKernelBranch .farField = .multipole := by
  rfl

/-- Mutable portion of the evaluator state.
    `pendingLevels` models the frontier payload, while `frontierMode` and
    `golayWeight` are frozen copies of the configuration for preservation lemmas. -/
structure FmmEvalState where
  pendingLevels : List ℕ
  currentLevel? : Option ℕ := none
  totalPotential : Potential := 0
  frontierMode : FrontierMode
  golayWeight : GolayWeight

/-- State-level invariants needed before any step relation is introduced. -/
def FmmEvalState.WellFormed (input : FmmInput) (state : FmmEvalState) : Prop :=
  state.frontierMode = input.config.frontierMode ∧
  state.golayWeight = input.config.golayWeight ∧
  (∀ level ∈ state.pendingLevels, level < input.hierarchy.length) ∧
  ∀ level, state.currentLevel? = some level → level < input.hierarchy.length

/-- Insert one level into the frontier using the runtime discipline.
    Stack mode pushes to the front; queue mode appends at the back. -/
def FmmEvalState.pushLevel (state : FmmEvalState) (level : ℕ) : FmmEvalState :=
  match state.frontierMode with
  | .stack => { state with pendingLevels := level :: state.pendingLevels }
  | .queue => { state with pendingLevels := state.pendingLevels ++ [level] }

/-- Pop the next frontier level and remember it as the current level. -/
def FmmEvalState.popLevel (state : FmmEvalState) : Option ℕ × FmmEvalState :=
  match state.pendingLevels with
  | [] => (none, { state with currentLevel? := none })
  | level :: rest =>
      (some level, { state with pendingLevels := rest, currentLevel? := some level })

@[simp]
theorem pushLevel_currentLevel? (state : FmmEvalState) (level : ℕ) :
    (state.pushLevel level).currentLevel? = state.currentLevel? := by
  cases hmode : state.frontierMode <;> simp [FmmEvalState.pushLevel, hmode]

@[simp]
theorem pushLevel_frontierMode (state : FmmEvalState) (level : ℕ) :
    (state.pushLevel level).frontierMode = state.frontierMode := by
  cases hmode : state.frontierMode <;> simp [FmmEvalState.pushLevel, hmode]

@[simp]
theorem pushLevel_golayWeight (state : FmmEvalState) (level : ℕ) :
    (state.pushLevel level).golayWeight = state.golayWeight := by
  cases hmode : state.frontierMode <;> simp [FmmEvalState.pushLevel, hmode]

@[simp]
theorem popLevel_frontierMode (state : FmmEvalState) :
    state.popLevel.2.frontierMode = state.frontierMode := by
  cases hpending : state.pendingLevels <;> simp [FmmEvalState.popLevel, hpending]

@[simp]
theorem popLevel_golayWeight (state : FmmEvalState) :
    state.popLevel.2.golayWeight = state.golayWeight := by
  cases hpending : state.pendingLevels <;> simp [FmmEvalState.popLevel, hpending]

theorem pushLevel_wellFormed
    {input : FmmInput} {state : FmmEvalState} {level : ℕ}
    (hstate : FmmEvalState.WellFormed input state)
    (hlevel : level < input.hierarchy.length) :
    FmmEvalState.WellFormed input (state.pushLevel level) := by
  rcases hstate with ⟨hmode, hweight, hpending, hcurrent⟩
  constructor
  · rw [pushLevel_frontierMode]
    exact hmode
  constructor
  · rw [pushLevel_golayWeight]
    exact hweight
  constructor
  · intro level' hmem
    cases hfrontier : state.frontierMode <;> simp [FmmEvalState.pushLevel, hfrontier] at hmem
    · rcases hmem with rfl | hmem
      · exact hlevel
      · exact hpending _ hmem
    · rcases hmem with hmem | hmem
      · exact hpending _ hmem
      · cases hmem
        exact hlevel
  · intro level' hcur
    rw [pushLevel_currentLevel?] at hcur
    exact hcurrent level' hcur

theorem popLevel_popped_inBounds
    {input : FmmInput} {state : FmmEvalState} {level : ℕ}
    (hstate : FmmEvalState.WellFormed input state)
    (hpop : state.popLevel.1 = some level) :
    level < input.hierarchy.length := by
  rcases hstate with ⟨_, _, hpending, _⟩
  cases hlevels : state.pendingLevels with
  | nil =>
      simp [FmmEvalState.popLevel, hlevels] at hpop
  | cons head tail =>
      simp [FmmEvalState.popLevel, hlevels] at hpop
      subst level
      exact hpending head (by simp [hlevels])

theorem popLevel_wellFormed
    {input : FmmInput} {state : FmmEvalState}
    (hstate : FmmEvalState.WellFormed input state) :
    FmmEvalState.WellFormed input state.popLevel.2 := by
  rcases hstate with ⟨hmode, hweight, hpending, hcurrent⟩
  cases hlevels : state.pendingLevels with
  | nil =>
      constructor
      · simpa [FmmEvalState.popLevel, hlevels] using hmode
      constructor
      · simpa [FmmEvalState.popLevel, hlevels] using hweight
      constructor
      · intro level hmem
        simp [FmmEvalState.popLevel, hlevels] at hmem
      · intro level hcur
        simp [FmmEvalState.popLevel, hlevels] at hcur
  | cons head tail =>
      constructor
      · simpa [FmmEvalState.popLevel, hlevels] using hmode
      constructor
      · simpa [FmmEvalState.popLevel, hlevels] using hweight
      constructor
      · intro level hmem
        have hmem' : level ∈ state.pendingLevels := by
          simpa [FmmEvalState.popLevel, hlevels] using List.mem_cons_of_mem head hmem
        exact hpending level hmem'
      · intro level hcur
        simp [FmmEvalState.popLevel, hlevels] at hcur
        subst level
        exact hpending head (by simp [hlevels])

/-- Lookup one cell in the hierarchy by traversal level. -/
def FmmHierarchy.cellAt? : FmmHierarchy → ℕ → Option FmmCell
  | [], _ => none
  | cell :: _, 0 => some cell
  | _ :: rest, level + 1 => FmmHierarchy.cellAt? rest level

/-- Lookup the hierarchy cell attached to one traversal level. -/
def FmmInput.cellAt? (input : FmmInput) (level : ℕ) : Option FmmCell :=
  FmmHierarchy.cellAt? input.hierarchy level

/-- Charge lookup aligned with the runtime `list-ref charges idx`. -/
noncomputable def FmmInput.chargeAt (input : FmmInput) (idx : ℕ) : Potential :=
  input.charges.getD idx 0

/-- One structural FMM step after popping the frontier.
    This records which level was selected, which cell it corresponds to,
    and what the frontier state looks like afterwards. -/
structure FmmStep where
  level : ℕ
  cell : FmmCell
  center : GoppaPoint
  distance : ℝ
  interactionKind : InteractionKind
  nextState : FmmEvalState

/-- Derived execution branch for one structural FMM step. -/
def FmmStep.kernelBranch (step : FmmStep) : KernelBranch :=
  step.interactionKind.toKernelBranch

@[simp]
theorem kernelBranch_eq_directSum_iff (step : FmmStep) :
    step.kernelBranch = .directSum ↔ step.interactionKind = .nearField := by
  cases h : step.interactionKind <;> simp [FmmStep.kernelBranch, InteractionKind.toKernelBranch, h]

@[simp]
theorem kernelBranch_eq_multipole_iff (step : FmmStep) :
    step.kernelBranch = .multipole ↔ step.interactionKind = .farField := by
  cases h : step.interactionKind <;> simp [FmmStep.kernelBranch, InteractionKind.toKernelBranch, h]

/-- One direct-sum term from the near-field runtime loop. -/
structure DirectSumTerm where
  sourceIdx : ℕ
  sourcePos : GoppaPoint
  diff : GoppaPoint
  charge : Potential
  contribution : Potential

/-- Near-field payload shell extracted from one successful FMM step. -/
structure DirectSumPayload where
  targetPos : GoppaPoint
  terms : List DirectSumTerm

/-- Build one direct-sum term the same way the runtime loop does. -/
noncomputable def FmmInput.directSumTerm (input : FmmInput) (sourceIdx : ℕ) : DirectSumTerm :=
  let sourcePos := input.grid.getD sourceIdx 0
  let diff := input.targetPos - sourcePos
  let charge := input.chargeAt sourceIdx
  let contribution :=
    if sourceIdx = input.targetIdx then 0 else charge / diff
  { sourceIdx, sourcePos, diff, charge, contribution }

/-- Gather the near-field payload carried by one step. -/
noncomputable def FmmInput.directSumPayload (input : FmmInput) (step : FmmStep) : DirectSumPayload :=
  { targetPos := input.targetPos
    terms :=
      (step.cell.sourceIndices.filter (fun idx => idx ≠ input.targetIdx)).map
        (input.directSumTerm) }

@[simp]
theorem directSumPayload_targetPos (input : FmmInput) (step : FmmStep) :
    (input.directSumPayload step).targetPos = input.targetPos := by
  rfl

@[simp]
theorem directSumPayload_terms (input : FmmInput) (step : FmmStep) :
    (input.directSumPayload step).terms =
      (step.cell.sourceIndices.filter (fun idx => idx ≠ input.targetIdx)).map (input.directSumTerm) := by
  rfl

/-- Build one structural step by popping the frontier and attaching the
    corresponding hierarchy cell. -/
noncomputable def FmmInput.step? (input : FmmInput) (state : FmmEvalState) : Option FmmStep :=
  match state.popLevel with
  | (none, _) => none
  | (some level, nextState) =>
      match input.cellAt? level with
      | none => none
      | some cell =>
          some
            { level
              cell
              center := input.cellCenter cell
              distance := input.cellDistance cell
              interactionKind := input.interactionKind cell
              nextState }

theorem step?_level_inBounds
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstate : FmmEvalState.WellFormed input state)
    (hstep : input.step? state = some step) :
    step.level < input.hierarchy.length := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              have hpop' : state.popLevel.1 = some level := by
                simp [hpop]
              exact popLevel_popped_inBounds (state := state) hstate hpop'

theorem step?_cellAt?_eq_some
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    input.cellAt? step.level = some step.cell := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              exact hcell

theorem step?_center_eq
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.center = input.cellCenter step.cell := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              rfl

theorem step?_distance_eq
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.distance = input.cellDistance step.cell := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              rfl

theorem step?_interactionKind_eq
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.interactionKind = input.interactionKind step.cell := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              rfl

theorem step?_kernelBranch_eq_directSum_iff
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.kernelBranch = .directSum ↔ input.isNearField step.cell := by
  rw [kernelBranch_eq_directSum_iff, step?_interactionKind_eq hstep, interactionKind_eq_nearField_iff]

theorem step?_kernelBranch_eq_multipole_iff
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.kernelBranch = .multipole ↔ ¬ input.isNearField step.cell := by
  rw [kernelBranch_eq_multipole_iff, step?_interactionKind_eq hstep, interactionKind_eq_farField_iff]

theorem step?_nextState_eq_popLevel
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.nextState = state.popLevel.2 := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              rfl

theorem step?_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstate : FmmEvalState.WellFormed input state)
    (hstep : input.step? state = some step) :
    FmmEvalState.WellFormed input step.nextState := by
  rw [step?_nextState_eq_popLevel hstep]
  exact popLevel_wellFormed hstate

/-- Direct-sum branch equipped with the explicit near-field payload. -/
inductive FmmDirectSumTransition (input : FmmInput) (state : FmmEvalState) :
    FmmStep → DirectSumPayload → Prop where
  | mk {step : FmmStep} {payload : DirectSumPayload} :
      input.step? state = some step →
      step.kernelBranch = .directSum →
      payload = input.directSumPayload step →
      FmmDirectSumTransition input state step payload

theorem step?_directSumTransition
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step)
    (hbranch : step.kernelBranch = .directSum) :
    FmmDirectSumTransition input state step (input.directSumPayload step) := by
  exact .mk hstep hbranch rfl

theorem directSumTransition_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : DirectSumPayload}
    (hstate : FmmEvalState.WellFormed input state)
    (htrans : FmmDirectSumTransition input state step payload) :
    FmmEvalState.WellFormed input step.nextState := by
  cases htrans with
  | mk hstep _ _ =>
      exact step?_nextState_wellFormed hstate hstep

/-- Far-field payload shell mirroring the runtime multipole setup data. -/
structure MultipolePayload where
  sourceIndices : List ℕ
  sourceCharges : List Potential
  center : GoppaPoint
  order : ℕ
  targetPos : GoppaPoint
  multipoleCoeffs : List Potential := []
  localCoeffs : List Potential := []

/-- Gather the far-field payload carried by one step. -/
noncomputable def FmmInput.multipolePayload (input : FmmInput) (step : FmmStep) : MultipolePayload :=
  { sourceIndices := step.cell.sourceIndices
    sourceCharges := step.cell.sourceIndices.map input.chargeAt
    center := step.center
    order := input.config.order
    targetPos := input.targetPos }

@[simp]
theorem multipolePayload_sourceIndices (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).sourceIndices = step.cell.sourceIndices := by
  rfl

@[simp]
theorem multipolePayload_sourceCharges (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).sourceCharges = step.cell.sourceIndices.map input.chargeAt := by
  rfl

@[simp]
theorem multipolePayload_center (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).center = step.center := by
  rfl

@[simp]
theorem multipolePayload_order (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).order = input.config.order := by
  rfl

@[simp]
theorem multipolePayload_targetPos (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).targetPos = input.targetPos := by
  rfl

/-- Multipole branch equipped with the explicit far-field payload. -/
inductive FmmMultipoleTransition (input : FmmInput) (state : FmmEvalState) :
    FmmStep → MultipolePayload → Prop where
  | mk {step : FmmStep} {payload : MultipolePayload} :
      input.step? state = some step →
      step.kernelBranch = .multipole →
      payload = input.multipolePayload step →
      FmmMultipoleTransition input state step payload

theorem step?_multipoleTransition
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step)
    (hbranch : step.kernelBranch = .multipole) :
    FmmMultipoleTransition input state step (input.multipolePayload step) := by
  exact .mk hstep hbranch rfl

theorem multipoleTransition_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : MultipolePayload}
    (hstate : FmmEvalState.WellFormed input state)
    (htrans : FmmMultipoleTransition input state step payload) :
    FmmEvalState.WellFormed input step.nextState := by
  cases htrans with
  | mk hstep _ _ =>
      exact step?_nextState_wellFormed hstate hstep

/-- Branch-specific semantic shell for one successful FMM step.
    Near-field steps expose a direct-sum branch, while far-field steps expose a multipole branch. -/
inductive FmmTransition (input : FmmInput) (state : FmmEvalState) : FmmStep → Prop where
  | directSum {step : FmmStep} :
      input.step? state = some step →
      step.kernelBranch = .directSum →
      step.distance < input.config.admissibilityRadius →
      FmmTransition input state step
  | multipole {step : FmmStep} :
      input.step? state = some step →
      step.kernelBranch = .multipole →
      input.config.admissibilityRadius ≤ step.distance →
      FmmTransition input state step

theorem step?_transition
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    FmmTransition input state step := by
  by_cases hnear : input.isNearField step.cell
  · apply FmmTransition.directSum hstep
    · exact (step?_kernelBranch_eq_directSum_iff hstep).2 hnear
    · have hdist : input.cellDistance step.cell < input.config.admissibilityRadius := by
        simpa [FmmInput.isNearField] using hnear
      rw [step?_distance_eq hstep]
      exact hdist
  · apply FmmTransition.multipole hstep
    · exact (step?_kernelBranch_eq_multipole_iff hstep).2 hnear
    · have hfar : input.config.admissibilityRadius ≤ input.cellDistance step.cell := by
        have hnot : ¬ input.cellDistance step.cell < input.config.admissibilityRadius := by
          simpa [FmmInput.isNearField] using hnear
        exact le_of_not_gt hnot
      rw [step?_distance_eq hstep]
      exact hfar

theorem transition_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstate : FmmEvalState.WellFormed input state)
    (htrans : FmmTransition input state step) :
    FmmEvalState.WellFormed input step.nextState := by
  cases htrans with
  | directSum hstep _ _ =>
      exact step?_nextState_wellFormed hstate hstep
  | multipole hstep _ _ =>
      exact step?_nextState_wellFormed hstate hstep

/-- Initial state: every hierarchy level is pending, and no potential has been accumulated. -/
def initialState (input : FmmInput) : FmmEvalState :=
  { pendingLevels := List.range input.hierarchy.length
    frontierMode := input.config.frontierMode
    golayWeight := input.config.golayWeight }

@[simp]
theorem initialState_frontierMode (input : FmmInput) :
    (initialState input).frontierMode = input.config.frontierMode := by
  rfl

@[simp]
theorem initialState_golayWeight (input : FmmInput) :
    (initialState input).golayWeight = input.config.golayWeight := by
  rfl

@[simp]
theorem mem_initialState_pendingLevels (input : FmmInput) (level : ℕ) :
    level ∈ (initialState input).pendingLevels ↔ level < input.hierarchy.length := by
  simp [initialState]

theorem initialState_wellFormed (input : FmmInput) :
    FmmEvalState.WellFormed input (initialState input) := by
  constructor
  · rfl
  constructor
  · rfl
  constructor
  · intro level hlevel
    simpa [initialState] using List.mem_range.mp hlevel
  · intro level hlevel
    simp [initialState] at hlevel

end HatsuYakitori.Fmm
