/-
Copyright (c) 2026 HatsuYakitori. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yoshihiro Hasegawa
-/

import HatsuYakitori.MachineConstants
import Mathlib.Data.Complex.Basic

namespace HatsuYakitori.Fmm

open HatsuYakitori.MachineConstants

/-!
# Golay-driven FMM State Model

This module replaces the autogenerated `FMM.lean` stub with a proof-friendly
state model for the runtime evaluator in
`modules/fmm/fmm_on_goppa_grid.scm`.

The goal of this first pass is intentionally narrow:

1. define the basic carriers used by a Golay-driven FMM evaluation,
2. expose the frontier mode as derived data from `GolayWeight`,
3. state well-formedness predicates for inputs and evaluation states,
4. provide the initial state from which later transition lemmas can start.

This follows the same style as `HopfStructure.lean`: set up small algebraic
containers and derived invariants before proving stronger algorithmic facts.
-/

/-- Points on the Goppa grid are represented by complex coordinates. -/
abbrev GoppaPoint := ℂ

/-- Accumulated FMM potential. -/
abbrev Potential := ℂ

/-- Frontier discipline chosen from the Golay-controlled entropy class. -/
inductive FrontierMode where
  | stack
  | queue
  deriving DecidableEq, Repr

/-- Runtime cells are currently represented by source indices only.
    This mirrors the Scheme hierarchy, where each level stores one list of indices. -/
structure FmmCell where
  sourceIndices : List ℕ

/-- The hierarchy processed by the evaluator, ordered by traversal level. -/
abbrev FmmHierarchy := List FmmCell

/-- Static configuration data for one FMM evaluation. -/
structure FmmConfig where
  order : ℕ
  admissibilityRadius : ℝ := 0.5
  golayWeight : GolayWeight := .w0

/-- A minimal positivity predicate for configuration parameters. -/
def FmmConfig.WellFormed (cfg : FmmConfig) : Prop :=
  0 < cfg.order ∧ 0 < cfg.admissibilityRadius

/-- The discrete Golay class seen by the runtime as a Hamming weight. -/
def FmmConfig.tau (cfg : FmmConfig) : ℕ :=
  cfg.golayWeight.toNat

/-- The corresponding logarithmic height used elsewhere in the Lean development. -/
noncomputable def FmmConfig.galoisHeight (cfg : FmmConfig) : ℝ :=
  HatsuYakitori.MachineConstants.galoisHeight cfg.tau

/-- Low Golay weight uses stack/DFS; dodecad-and-above uses queue/BFS.
    This matches the runtime split at `τ = 12`. -/
def FrontierMode.ofTau (tau : ℕ) : FrontierMode :=
  if tau < 12 then .stack else .queue

/-- Frontier mode derived from the Golay weight class. -/
def FrontierMode.ofGolayWeight (w : GolayWeight) : FrontierMode :=
  FrontierMode.ofTau w.toNat

/-- The frontier mode selected by the configuration. -/
def FmmConfig.frontierMode (cfg : FmmConfig) : FrontierMode :=
  FrontierMode.ofGolayWeight cfg.golayWeight

/-- All external data required to run one FMM evaluation. -/
structure FmmInput where
  grid : List GoppaPoint
  hierarchy : FmmHierarchy
  sources : List ℕ := []
  charges : List Potential
  targetIdx : ℕ
  config : FmmConfig

/-- Input-level well-formedness, kept intentionally lightweight for the first pass. -/
def FmmInput.WellFormed (input : FmmInput) : Prop :=
  input.config.WellFormed ∧
  input.targetIdx < input.grid.length ∧
  input.charges.length = input.grid.length ∧
  (∀ idx ∈ input.sources, idx < input.grid.length) ∧
  (∀ cell ∈ input.hierarchy, ∀ idx ∈ cell.sourceIndices, idx < input.grid.length)

/-- The target point being evaluated. Defaults to `0` outside the well-formed regime. -/
noncomputable def FmmInput.targetPos (input : FmmInput) : GoppaPoint :=
  input.grid.getD input.targetIdx 0

/-- Geometric center of a cell, computed as the average of its indexed grid points. -/
noncomputable def FmmInput.cellCenter (input : FmmInput) (cell : FmmCell) : GoppaPoint :=
  match cell.sourceIndices with
  | [] => 0
  | _ =>
      let sum := cell.sourceIndices.foldl (fun acc idx => acc + input.grid.getD idx 0) 0
      sum / (cell.sourceIndices.length : ℂ)

/-- Distance from the target point to a cell center. -/
noncomputable def FmmInput.cellDistance (input : FmmInput) (cell : FmmCell) : ℝ :=
  ‖input.targetPos - input.cellCenter cell‖

@[simp]
theorem cellDistance_nonneg (input : FmmInput) (cell : FmmCell) :
    0 ≤ input.cellDistance cell := by
  simp [FmmInput.cellDistance]

/-- Near-field predicate matching the current runtime cutoff style. -/
noncomputable def FmmInput.isNearField (input : FmmInput) (cell : FmmCell) : Prop :=
  input.cellDistance cell < input.config.admissibilityRadius

/-- Classification of one interaction cell in the current FMM step. -/
inductive InteractionKind where
  | nearField
  | farField
  deriving DecidableEq, Repr

/-- Runtime branch selected from the geometric near/far classification. -/
inductive KernelBranch where
  | directSum
  | multipole
  deriving DecidableEq, Repr

/-- Convert the geometric cutoff predicate into an explicit runtime tag. -/
noncomputable def FmmInput.interactionKind (input : FmmInput) (cell : FmmCell) : InteractionKind := by
  classical
  exact if input.isNearField cell then .nearField else .farField

@[simp]
theorem interactionKind_eq_nearField_iff (input : FmmInput) (cell : FmmCell) :
    input.interactionKind cell = .nearField ↔ input.isNearField cell := by
  classical
  simp [FmmInput.interactionKind]

@[simp]
theorem interactionKind_eq_farField_iff (input : FmmInput) (cell : FmmCell) :
    input.interactionKind cell = .farField ↔ ¬ input.isNearField cell := by
  classical
  simp [FmmInput.interactionKind]

/-- Near-field cells run the direct summation branch; far-field cells run the multipole branch. -/
def InteractionKind.toKernelBranch : InteractionKind → KernelBranch
  | .nearField => .directSum
  | .farField => .multipole

@[simp]
theorem toKernelBranch_nearField :
    InteractionKind.toKernelBranch .nearField = .directSum := by
  rfl

@[simp]
theorem toKernelBranch_farField :
    InteractionKind.toKernelBranch .farField = .multipole := by
  rfl

/-- Mutable portion of the evaluator state.
    `pendingLevels` models the frontier payload, while `frontierMode` and
    `golayWeight` are frozen copies of the configuration for preservation lemmas. -/
structure FmmEvalState where
  pendingLevels : List ℕ
  currentLevel? : Option ℕ := none
  totalPotential : Potential := 0
  frontierMode : FrontierMode
  golayWeight : GolayWeight

/-- State-level invariants needed before any step relation is introduced. -/
def FmmEvalState.WellFormed (input : FmmInput) (state : FmmEvalState) : Prop :=
  state.frontierMode = input.config.frontierMode ∧
  state.golayWeight = input.config.golayWeight ∧
  (∀ level ∈ state.pendingLevels, level < input.hierarchy.length) ∧
  ∀ level, state.currentLevel? = some level → level < input.hierarchy.length

/-- Insert one level into the frontier using the runtime discipline.
    Stack mode pushes to the front; queue mode appends at the back. -/
def FmmEvalState.pushLevel (state : FmmEvalState) (level : ℕ) : FmmEvalState :=
  match state.frontierMode with
  | .stack => { state with pendingLevels := level :: state.pendingLevels }
  | .queue => { state with pendingLevels := state.pendingLevels ++ [level] }

/-- Pop the next frontier level and remember it as the current level. -/
def FmmEvalState.popLevel (state : FmmEvalState) : Option ℕ × FmmEvalState :=
  match state.pendingLevels with
  | [] => (none, { state with currentLevel? := none })
  | level :: rest =>
      (some level, { state with pendingLevels := rest, currentLevel? := some level })

@[simp]
theorem pushLevel_currentLevel? (state : FmmEvalState) (level : ℕ) :
    (state.pushLevel level).currentLevel? = state.currentLevel? := by
  cases hmode : state.frontierMode <;> simp [FmmEvalState.pushLevel, hmode]

@[simp]
theorem pushLevel_frontierMode (state : FmmEvalState) (level : ℕ) :
    (state.pushLevel level).frontierMode = state.frontierMode := by
  cases hmode : state.frontierMode <;> simp [FmmEvalState.pushLevel, hmode]

@[simp]
theorem pushLevel_golayWeight (state : FmmEvalState) (level : ℕ) :
    (state.pushLevel level).golayWeight = state.golayWeight := by
  cases hmode : state.frontierMode <;> simp [FmmEvalState.pushLevel, hmode]

@[simp]
theorem popLevel_frontierMode (state : FmmEvalState) :
    state.popLevel.2.frontierMode = state.frontierMode := by
  cases hpending : state.pendingLevels <;> simp [FmmEvalState.popLevel, hpending]

@[simp]
theorem popLevel_golayWeight (state : FmmEvalState) :
    state.popLevel.2.golayWeight = state.golayWeight := by
  cases hpending : state.pendingLevels <;> simp [FmmEvalState.popLevel, hpending]

theorem pushLevel_wellFormed
    {input : FmmInput} {state : FmmEvalState} {level : ℕ}
    (hstate : FmmEvalState.WellFormed input state)
    (hlevel : level < input.hierarchy.length) :
    FmmEvalState.WellFormed input (state.pushLevel level) := by
  rcases hstate with ⟨hmode, hweight, hpending, hcurrent⟩
  constructor
  · rw [pushLevel_frontierMode]
    exact hmode
  constructor
  · rw [pushLevel_golayWeight]
    exact hweight
  constructor
  · intro level' hmem
    cases hfrontier : state.frontierMode <;> simp [FmmEvalState.pushLevel, hfrontier] at hmem
    · rcases hmem with rfl | hmem
      · exact hlevel
      · exact hpending _ hmem
    · rcases hmem with hmem | hmem
      · exact hpending _ hmem
      · cases hmem
        exact hlevel
  · intro level' hcur
    rw [pushLevel_currentLevel?] at hcur
    exact hcurrent level' hcur

theorem popLevel_popped_inBounds
    {input : FmmInput} {state : FmmEvalState} {level : ℕ}
    (hstate : FmmEvalState.WellFormed input state)
    (hpop : state.popLevel.1 = some level) :
    level < input.hierarchy.length := by
  rcases hstate with ⟨_, _, hpending, _⟩
  cases hlevels : state.pendingLevels with
  | nil =>
      simp [FmmEvalState.popLevel, hlevels] at hpop
  | cons head tail =>
      simp [FmmEvalState.popLevel, hlevels] at hpop
      subst level
      exact hpending head (by simp [hlevels])

theorem popLevel_wellFormed
    {input : FmmInput} {state : FmmEvalState}
    (hstate : FmmEvalState.WellFormed input state) :
    FmmEvalState.WellFormed input state.popLevel.2 := by
  rcases hstate with ⟨hmode, hweight, hpending, hcurrent⟩
  cases hlevels : state.pendingLevels with
  | nil =>
      constructor
      · simpa [FmmEvalState.popLevel, hlevels] using hmode
      constructor
      · simpa [FmmEvalState.popLevel, hlevels] using hweight
      constructor
      · intro level hmem
        simp [FmmEvalState.popLevel, hlevels] at hmem
      · intro level hcur
        simp [FmmEvalState.popLevel, hlevels] at hcur
  | cons head tail =>
      constructor
      · simpa [FmmEvalState.popLevel, hlevels] using hmode
      constructor
      · simpa [FmmEvalState.popLevel, hlevels] using hweight
      constructor
      · intro level hmem
        have hmem' : level ∈ state.pendingLevels := by
          simpa [FmmEvalState.popLevel, hlevels] using List.mem_cons_of_mem head hmem
        exact hpending level hmem'
      · intro level hcur
        simp [FmmEvalState.popLevel, hlevels] at hcur
        subst level
        exact hpending head (by simp [hlevels])

/-- Lookup one cell in the hierarchy by traversal level. -/
def FmmHierarchy.cellAt? : FmmHierarchy → ℕ → Option FmmCell
  | [], _ => none
  | cell :: _, 0 => some cell
  | _ :: rest, level + 1 => FmmHierarchy.cellAt? rest level

/-- Lookup the hierarchy cell attached to one traversal level. -/
def FmmInput.cellAt? (input : FmmInput) (level : ℕ) : Option FmmCell :=
  FmmHierarchy.cellAt? input.hierarchy level

/-- Charge lookup aligned with the runtime `list-ref charges idx`. -/
noncomputable def FmmInput.chargeAt (input : FmmInput) (idx : ℕ) : Potential :=
  input.charges.getD idx 0

/-- One structural FMM step after popping the frontier.
    This records which level was selected, which cell it corresponds to,
    and what the frontier state looks like afterwards. -/
structure FmmStep where
  level : ℕ
  cell : FmmCell
  center : GoppaPoint
  distance : ℝ
  interactionKind : InteractionKind
  nextState : FmmEvalState

/-- Derived execution branch for one structural FMM step. -/
def FmmStep.kernelBranch (step : FmmStep) : KernelBranch :=
  step.interactionKind.toKernelBranch

@[simp]
theorem kernelBranch_eq_directSum_iff (step : FmmStep) :
    step.kernelBranch = .directSum ↔ step.interactionKind = .nearField := by
  cases h : step.interactionKind <;> simp [FmmStep.kernelBranch, InteractionKind.toKernelBranch, h]

@[simp]
theorem kernelBranch_eq_multipole_iff (step : FmmStep) :
    step.kernelBranch = .multipole ↔ step.interactionKind = .farField := by
  cases h : step.interactionKind <;> simp [FmmStep.kernelBranch, InteractionKind.toKernelBranch, h]

/-- One direct-sum term from the near-field runtime loop. -/
structure DirectSumTerm where
  sourceIdx : ℕ
  sourcePos : GoppaPoint
  diff : GoppaPoint
  charge : Potential
  contribution : Potential

/-- Near-field payload shell extracted from one successful FMM step. -/
structure DirectSumPayload where
  targetPos : GoppaPoint
  terms : List DirectSumTerm

/-- Build one direct-sum term the same way the runtime loop does. -/
noncomputable def FmmInput.directSumTerm (input : FmmInput) (sourceIdx : ℕ) : DirectSumTerm :=
  let sourcePos := input.grid.getD sourceIdx 0
  let diff := input.targetPos - sourcePos
  let charge := input.chargeAt sourceIdx
  let contribution :=
    if sourceIdx = input.targetIdx then 0 else charge / diff
  { sourceIdx, sourcePos, diff, charge, contribution }

/-- Gather the near-field payload carried by one step. -/
noncomputable def FmmInput.directSumPayload (input : FmmInput) (step : FmmStep) : DirectSumPayload :=
  { targetPos := input.targetPos
    terms :=
      (step.cell.sourceIndices.filter (fun idx => idx ≠ input.targetIdx)).map
        (input.directSumTerm) }

@[simp]
theorem directSumPayload_targetPos (input : FmmInput) (step : FmmStep) :
    (input.directSumPayload step).targetPos = input.targetPos := by
  rfl

@[simp]
theorem directSumPayload_terms (input : FmmInput) (step : FmmStep) :
    (input.directSumPayload step).terms =
      (step.cell.sourceIndices.filter (fun idx => idx ≠ input.targetIdx)).map (input.directSumTerm) := by
  rfl

/-- Sum of all near-field contributions carried by one direct-sum payload. -/
noncomputable def DirectSumPayload.totalContribution (payload : DirectSumPayload) : Potential :=
  payload.terms.foldl (fun acc term => acc + term.contribution) 0

/-- Apply one direct-sum payload to the accumulated potential while leaving the frontier untouched. -/
noncomputable def FmmEvalState.applyDirectSum
    (state : FmmEvalState) (payload : DirectSumPayload) : FmmEvalState :=
  { state with totalPotential := state.totalPotential + payload.totalContribution }

@[simp]
theorem applyDirectSum_pendingLevels (state : FmmEvalState) (payload : DirectSumPayload) :
    (state.applyDirectSum payload).pendingLevels = state.pendingLevels := by
  rfl

@[simp]
theorem applyDirectSum_currentLevel? (state : FmmEvalState) (payload : DirectSumPayload) :
    (state.applyDirectSum payload).currentLevel? = state.currentLevel? := by
  rfl

@[simp]
theorem applyDirectSum_frontierMode (state : FmmEvalState) (payload : DirectSumPayload) :
    (state.applyDirectSum payload).frontierMode = state.frontierMode := by
  rfl

@[simp]
theorem applyDirectSum_golayWeight (state : FmmEvalState) (payload : DirectSumPayload) :
    (state.applyDirectSum payload).golayWeight = state.golayWeight := by
  rfl

@[simp]
theorem applyDirectSum_totalPotential (state : FmmEvalState) (payload : DirectSumPayload) :
    (state.applyDirectSum payload).totalPotential = state.totalPotential + payload.totalContribution := by
  rfl

theorem applyDirectSum_wellFormed
    {input : FmmInput} {state : FmmEvalState} {payload : DirectSumPayload}
    (hstate : FmmEvalState.WellFormed input state) :
    FmmEvalState.WellFormed input (state.applyDirectSum payload) := by
  rcases hstate with ⟨hmode, hweight, hpending, hcurrent⟩
  constructor
  · simpa [FmmEvalState.applyDirectSum] using hmode
  constructor
  · simpa [FmmEvalState.applyDirectSum] using hweight
  constructor
  · simpa [FmmEvalState.applyDirectSum] using hpending
  · simpa [FmmEvalState.applyDirectSum] using hcurrent

/-- Build one structural step by popping the frontier and attaching the
    corresponding hierarchy cell. -/
noncomputable def FmmInput.step? (input : FmmInput) (state : FmmEvalState) : Option FmmStep :=
  match state.popLevel with
  | (none, _) => none
  | (some level, nextState) =>
      match input.cellAt? level with
      | none => none
      | some cell =>
          some
            { level
              cell
              center := input.cellCenter cell
              distance := input.cellDistance cell
              interactionKind := input.interactionKind cell
              nextState }

theorem step?_level_inBounds
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstate : FmmEvalState.WellFormed input state)
    (hstep : input.step? state = some step) :
    step.level < input.hierarchy.length := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              have hpop' : state.popLevel.1 = some level := by
                simp [hpop]
              exact popLevel_popped_inBounds (state := state) hstate hpop'

theorem step?_cellAt?_eq_some
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    input.cellAt? step.level = some step.cell := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              exact hcell

theorem step?_center_eq
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.center = input.cellCenter step.cell := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              rfl

theorem step?_distance_eq
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.distance = input.cellDistance step.cell := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              rfl

theorem step?_interactionKind_eq
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.interactionKind = input.interactionKind step.cell := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              rfl

theorem step?_kernelBranch_eq_directSum_iff
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.kernelBranch = .directSum ↔ input.isNearField step.cell := by
  rw [kernelBranch_eq_directSum_iff, step?_interactionKind_eq hstep, interactionKind_eq_nearField_iff]

theorem step?_kernelBranch_eq_multipole_iff
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.kernelBranch = .multipole ↔ ¬ input.isNearField step.cell := by
  rw [kernelBranch_eq_multipole_iff, step?_interactionKind_eq hstep, interactionKind_eq_farField_iff]

theorem step?_nextState_eq_popLevel
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    step.nextState = state.popLevel.2 := by
  cases hpop : state.popLevel with
  | mk popped nextState =>
      cases popped with
      | none =>
          simp [FmmInput.step?, hpop] at hstep
      | some level =>
          cases hcell : input.cellAt? level with
          | none =>
              simp [FmmInput.step?, hpop, hcell] at hstep
          | some cell =>
              simp [FmmInput.step?, hpop, hcell] at hstep
              rcases hstep with rfl
              rfl

theorem step?_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstate : FmmEvalState.WellFormed input state)
    (hstep : input.step? state = some step) :
    FmmEvalState.WellFormed input step.nextState := by
  rw [step?_nextState_eq_popLevel hstep]
  exact popLevel_wellFormed hstate

/-- Direct-sum branch equipped with the explicit near-field payload. -/
inductive FmmDirectSumTransition (input : FmmInput) (state : FmmEvalState) :
    FmmStep → DirectSumPayload → Prop where
  | mk {step : FmmStep} {payload : DirectSumPayload} :
      input.step? state = some step →
      step.kernelBranch = .directSum →
      payload = input.directSumPayload step →
      FmmDirectSumTransition input state step payload

theorem step?_directSumTransition
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step)
    (hbranch : step.kernelBranch = .directSum) :
    FmmDirectSumTransition input state step (input.directSumPayload step) := by
  exact .mk hstep hbranch rfl

theorem directSumTransition_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : DirectSumPayload}
    (hstate : FmmEvalState.WellFormed input state)
    (htrans : FmmDirectSumTransition input state step payload) :
    FmmEvalState.WellFormed input step.nextState := by
  cases htrans with
  | mk hstep _ _ =>
      exact step?_nextState_wellFormed hstate hstep

/-- One near-field update that adds the direct-sum payload into the accumulated potential. -/
inductive FmmDirectSumUpdate (input : FmmInput) (state : FmmEvalState) :
    FmmStep → DirectSumPayload → FmmEvalState → Prop where
  | mk {step : FmmStep} {payload : DirectSumPayload} {updatedState : FmmEvalState} :
      FmmDirectSumTransition input state step payload →
      updatedState = step.nextState.applyDirectSum payload →
      FmmDirectSumUpdate input state step payload updatedState

theorem step?_directSumUpdate
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step)
    (hbranch : step.kernelBranch = .directSum) :
    FmmDirectSumUpdate input state step (input.directSumPayload step)
      (step.nextState.applyDirectSum (input.directSumPayload step)) := by
  apply FmmDirectSumUpdate.mk
  · exact step?_directSumTransition hstep hbranch
  · rfl

theorem directSumUpdate_totalPotential
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    {payload : DirectSumPayload} {updatedState : FmmEvalState}
    (hupdate : FmmDirectSumUpdate input state step payload updatedState) :
    updatedState.totalPotential = step.nextState.totalPotential + payload.totalContribution := by
  cases hupdate with
  | mk _ hupdated =>
      rw [hupdated]
      simp [FmmEvalState.applyDirectSum]

theorem directSumUpdate_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    {payload : DirectSumPayload} {updatedState : FmmEvalState}
    (hstate : FmmEvalState.WellFormed input state)
    (hupdate : FmmDirectSumUpdate input state step payload updatedState) :
    FmmEvalState.WellFormed input updatedState := by
  cases hupdate with
  | mk htrans hupdated =>
      rw [hupdated]
      exact applyDirectSum_wellFormed (directSumTransition_nextState_wellFormed hstate htrans)

/-- Placeholder coefficient vectors sized by the requested truncation order. -/
def zeroCoeffs (order : ℕ) : List Potential :=
  List.replicate order 0

@[simp]
theorem zeroCoeffs_length (order : ℕ) :
    (zeroCoeffs order).length = order := by
  simp [zeroCoeffs]

/-- Far-field payload shell mirroring the runtime multipole setup data. -/
structure MultipolePayload where
  sourceIndices : List ℕ
  sourceCharges : List Potential
  center : GoppaPoint
  order : ℕ
  targetPos : GoppaPoint
  multipoleCoeffs : List Potential := []
  localCoeffs : List Potential := []

/-- Structural invariants for the far-field payload shell. -/
def MultipolePayload.WellFormed (payload : MultipolePayload) : Prop :=
  payload.sourceIndices.length = payload.sourceCharges.length ∧
  payload.multipoleCoeffs.length = payload.order ∧
  payload.localCoeffs.length = payload.order

/-- Runtime far-field evaluation reads the zeroth local coefficient. -/
noncomputable def MultipolePayload.leadingLocalCoeff (payload : MultipolePayload) : Potential :=
  payload.localCoeffs.getD 0 0

/-- P2M coefficients matching the runtime source accumulation. -/
noncomputable def FmmInput.p2mCoeffs (input : FmmInput) (payload : MultipolePayload) :
    List Potential :=
  (List.range payload.order).map fun k =>
    (payload.sourceIndices.zip payload.sourceCharges).foldl
      (fun acc source =>
        let sourcePos := input.grid.getD source.1 0
        let delta := sourcePos - payload.center
        acc + source.2 * delta ^ k)
      0

/-- M2L coefficients matching the runtime binomial translation. -/
noncomputable def FmmInput.m2lCoeffs (_input : FmmInput) (payload : MultipolePayload) :
    List Potential :=
  let zDiff := payload.targetPos - payload.center
  (List.range payload.order).map fun j =>
    (List.range payload.order).foldl
      (fun acc k =>
        let coeff := payload.multipoleCoeffs.getD k 0
        let binom : Potential := (Nat.choose (j + k) k : ℂ)
        let signedBinom := if k % 2 = 0 then binom else -binom
        let factor := signedBinom / (zDiff ^ (j + k + 1))
        acc + coeff * factor)
      0

@[simp]
theorem p2mCoeffs_length (input : FmmInput) (payload : MultipolePayload) :
    (input.p2mCoeffs payload).length = payload.order := by
  simp [FmmInput.p2mCoeffs]

@[simp]
theorem m2lCoeffs_length (input : FmmInput) (payload : MultipolePayload) :
    (input.m2lCoeffs payload).length = payload.order := by
  simp [FmmInput.m2lCoeffs]

/-- Gather the far-field payload carried by one step. -/
noncomputable def FmmInput.multipolePayload (input : FmmInput) (step : FmmStep) : MultipolePayload :=
  let basePayload : MultipolePayload :=
    { sourceIndices := step.cell.sourceIndices
      sourceCharges := step.cell.sourceIndices.map input.chargeAt
      center := step.center
      order := input.config.order
      targetPos := input.targetPos
      multipoleCoeffs := zeroCoeffs input.config.order
      localCoeffs := zeroCoeffs input.config.order }
  let p2mPayload : MultipolePayload :=
    { basePayload with multipoleCoeffs := input.p2mCoeffs basePayload }
  { p2mPayload with localCoeffs := input.m2lCoeffs p2mPayload }

@[simp]
theorem multipolePayload_sourceIndices (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).sourceIndices = step.cell.sourceIndices := by
  rfl

@[simp]
theorem multipolePayload_sourceCharges (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).sourceCharges = step.cell.sourceIndices.map input.chargeAt := by
  rfl

@[simp]
theorem multipolePayload_center (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).center = step.center := by
  rfl

@[simp]
theorem multipolePayload_order (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).order = input.config.order := by
  rfl

@[simp]
theorem multipolePayload_targetPos (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).targetPos = input.targetPos := by
  rfl

@[simp]
theorem multipolePayload_multipoleCoeffs_length (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).multipoleCoeffs.length = input.config.order := by
  simp [FmmInput.multipolePayload, zeroCoeffs]

@[simp]
theorem multipolePayload_localCoeffs_length (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).localCoeffs.length = input.config.order := by
  simp [FmmInput.multipolePayload, zeroCoeffs]

theorem multipolePayload_wellFormed (input : FmmInput) (step : FmmStep) :
    MultipolePayload.WellFormed (input.multipolePayload step) := by
  constructor
  · simp [FmmInput.multipolePayload]
  constructor
  · simp [FmmInput.multipolePayload, zeroCoeffs]
  · simp [FmmInput.multipolePayload, zeroCoeffs]

@[simp]
theorem multipolePayload_multipoleCoeffs_eq_p2mCoeffs (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).multipoleCoeffs =
      input.p2mCoeffs (input.multipolePayload step) := by
  simp [FmmInput.multipolePayload, FmmInput.p2mCoeffs, FmmInput.m2lCoeffs]

@[simp]
theorem multipolePayload_localCoeffs_eq_m2lCoeffs (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).localCoeffs =
      input.m2lCoeffs (input.multipolePayload step) := by
  simp [FmmInput.multipolePayload, FmmInput.p2mCoeffs, FmmInput.m2lCoeffs]

@[simp]
theorem multipolePayload_leadingLocalCoeff_eq_m2lHead (input : FmmInput) (step : FmmStep) :
    (input.multipolePayload step).leadingLocalCoeff =
      (input.m2lCoeffs (input.multipolePayload step)).getD 0 0 := by
  simp [MultipolePayload.leadingLocalCoeff]

/-- Multipole branch equipped with the explicit far-field payload. -/
inductive FmmMultipoleTransition (input : FmmInput) (state : FmmEvalState) :
    FmmStep → MultipolePayload → Prop where
  | mk {step : FmmStep} {payload : MultipolePayload} :
      input.step? state = some step →
      step.kernelBranch = .multipole →
      payload = input.multipolePayload step →
      FmmMultipoleTransition input state step payload

theorem step?_multipoleTransition
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step)
    (hbranch : step.kernelBranch = .multipole) :
    FmmMultipoleTransition input state step (input.multipolePayload step) := by
  exact .mk hstep hbranch rfl

theorem multipoleTransition_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : MultipolePayload}
    (hstate : FmmEvalState.WellFormed input state)
    (htrans : FmmMultipoleTransition input state step payload) :
    FmmEvalState.WellFormed input step.nextState := by
  cases htrans with
  | mk hstep _ _ =>
      exact step?_nextState_wellFormed hstate hstep

theorem multipoleTransition_payload_wellFormed
  {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : MultipolePayload}
  (htrans : FmmMultipoleTransition input state step payload) :
  MultipolePayload.WellFormed payload := by
  rcases htrans with ⟨hstep, _, hpayload⟩
  simpa [hpayload] using (multipolePayload_wellFormed input step)

/-- The P2M stage fixes the multipole coefficient vector attached to a far-field payload. -/
inductive FmmP2MExpansion (input : FmmInput) (state : FmmEvalState) :
    FmmStep → MultipolePayload → Prop where
  | mk {step : FmmStep} {payload : MultipolePayload} :
      FmmMultipoleTransition input state step payload →
      payload.multipoleCoeffs = input.p2mCoeffs payload →
      FmmP2MExpansion input state step payload

theorem step?_p2mExpansion
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step)
    (hbranch : step.kernelBranch = .multipole) :
    FmmP2MExpansion input state step (input.multipolePayload step) := by
  apply FmmP2MExpansion.mk
  · exact step?_multipoleTransition hstep hbranch
  · exact multipolePayload_multipoleCoeffs_eq_p2mCoeffs input step

theorem p2mExpansion_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : MultipolePayload}
    (hstate : FmmEvalState.WellFormed input state)
    (hexp : FmmP2MExpansion input state step payload) :
    FmmEvalState.WellFormed input step.nextState := by
  cases hexp with
  | mk htrans _ =>
      exact multipoleTransition_nextState_wellFormed hstate htrans

theorem p2mExpansion_payload_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : MultipolePayload}
    (hexp : FmmP2MExpansion input state step payload) :
    MultipolePayload.WellFormed payload := by
  cases hexp with
  | mk htrans _ =>
      exact multipoleTransition_payload_wellFormed htrans

/-- The M2L stage fixes the translated local coefficient vector. -/
inductive FmmM2LTranslation (input : FmmInput) (state : FmmEvalState) :
    FmmStep → MultipolePayload → Prop where
  | mk {step : FmmStep} {payload : MultipolePayload} :
      FmmP2MExpansion input state step payload →
      payload.localCoeffs = input.m2lCoeffs payload →
      FmmM2LTranslation input state step payload

theorem step?_m2lTranslation
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step)
    (hbranch : step.kernelBranch = .multipole) :
    FmmM2LTranslation input state step (input.multipolePayload step) := by
  apply FmmM2LTranslation.mk
  · exact step?_p2mExpansion hstep hbranch
  · exact multipolePayload_localCoeffs_eq_m2lCoeffs input step

theorem m2lTranslation_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : MultipolePayload}
    (hstate : FmmEvalState.WellFormed input state)
    (htrans : FmmM2LTranslation input state step payload) :
    FmmEvalState.WellFormed input step.nextState := by
  cases htrans with
  | mk hexp _ =>
      exact p2mExpansion_nextState_wellFormed hstate hexp

theorem m2lTranslation_payload_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : MultipolePayload}
    (htrans : FmmM2LTranslation input state step payload) :
    MultipolePayload.WellFormed payload := by
  cases htrans with
  | mk hexp _ =>
      exact p2mExpansion_payload_wellFormed hexp

theorem m2lTranslation_leadingLocalCoeff_eq_m2lHead
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep} {payload : MultipolePayload}
    (htrans : FmmM2LTranslation input state step payload) :
    payload.leadingLocalCoeff = (input.m2lCoeffs payload).getD 0 0 := by
  cases htrans with
  | mk hexp hlocal =>
    simp [MultipolePayload.leadingLocalCoeff, hlocal]

/-- Apply one multipole payload to the accumulated potential via the zeroth local coefficient. -/
noncomputable def FmmEvalState.applyMultipole
    (state : FmmEvalState) (payload : MultipolePayload) : FmmEvalState :=
  { state with totalPotential := state.totalPotential + payload.leadingLocalCoeff }

@[simp]
theorem applyMultipole_pendingLevels (state : FmmEvalState) (payload : MultipolePayload) :
    (state.applyMultipole payload).pendingLevels = state.pendingLevels := by
  rfl

@[simp]
theorem applyMultipole_currentLevel? (state : FmmEvalState) (payload : MultipolePayload) :
    (state.applyMultipole payload).currentLevel? = state.currentLevel? := by
  rfl

@[simp]
theorem applyMultipole_frontierMode (state : FmmEvalState) (payload : MultipolePayload) :
    (state.applyMultipole payload).frontierMode = state.frontierMode := by
  rfl

@[simp]
theorem applyMultipole_golayWeight (state : FmmEvalState) (payload : MultipolePayload) :
    (state.applyMultipole payload).golayWeight = state.golayWeight := by
  rfl

@[simp]
theorem applyMultipole_totalPotential (state : FmmEvalState) (payload : MultipolePayload) :
    (state.applyMultipole payload).totalPotential = state.totalPotential + payload.leadingLocalCoeff := by
  rfl

theorem applyMultipole_wellFormed
    {input : FmmInput} {state : FmmEvalState} {payload : MultipolePayload}
    (hstate : FmmEvalState.WellFormed input state) :
    FmmEvalState.WellFormed input (state.applyMultipole payload) := by
  rcases hstate with ⟨hmode, hweight, hpending, hcurrent⟩
  constructor
  · simpa [FmmEvalState.applyMultipole] using hmode
  constructor
  · simpa [FmmEvalState.applyMultipole] using hweight
  constructor
  · simpa [FmmEvalState.applyMultipole] using hpending
  · simpa [FmmEvalState.applyMultipole] using hcurrent

/-- One far-field update that adds the zeroth local coefficient into the accumulated potential. -/
inductive FmmMultipoleUpdate (input : FmmInput) (state : FmmEvalState) :
    FmmStep → MultipolePayload → FmmEvalState → Prop where
  | mk {step : FmmStep} {payload : MultipolePayload} {updatedState : FmmEvalState} :
      FmmM2LTranslation input state step payload →
      updatedState = step.nextState.applyMultipole payload →
      FmmMultipoleUpdate input state step payload updatedState

theorem step?_multipoleUpdate
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step)
    (hbranch : step.kernelBranch = .multipole) :
    FmmMultipoleUpdate input state step (input.multipolePayload step)
      (step.nextState.applyMultipole (input.multipolePayload step)) := by
  apply FmmMultipoleUpdate.mk
  · exact step?_m2lTranslation hstep hbranch
  · rfl

theorem multipoleUpdate_totalPotential
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    {payload : MultipolePayload} {updatedState : FmmEvalState}
    (hupdate : FmmMultipoleUpdate input state step payload updatedState) :
    updatedState.totalPotential = step.nextState.totalPotential + payload.leadingLocalCoeff := by
  cases hupdate with
  | mk _ hupdated =>
      rw [hupdated]
      simp [FmmEvalState.applyMultipole]

theorem multipoleUpdate_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    {payload : MultipolePayload} {updatedState : FmmEvalState}
    (hstate : FmmEvalState.WellFormed input state)
    (hupdate : FmmMultipoleUpdate input state step payload updatedState) :
    FmmEvalState.WellFormed input updatedState := by
  cases hupdate with
  | mk htrans hupdated =>
      rw [hupdated]
      exact applyMultipole_wellFormed (m2lTranslation_nextState_wellFormed hstate htrans)

theorem multipoleUpdate_addsLeadingM2LHead
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    {payload : MultipolePayload} {updatedState : FmmEvalState}
    (hupdate : FmmMultipoleUpdate input state step payload updatedState) :
    updatedState.totalPotential =
      step.nextState.totalPotential + (input.m2lCoeffs payload).getD 0 0 := by
  cases hupdate with
  | mk htrans hupdated =>
      rw [hupdated, FmmEvalState.applyMultipole]
      have hhead := m2lTranslation_leadingLocalCoeff_eq_m2lHead htrans
      simp [hhead]

theorem step?_multipoleUpdate_addsLeadingM2LHead
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
  (_hstep : input.step? state = some step)
  (_hbranch : step.kernelBranch = .multipole) :
    (step.nextState.applyMultipole (input.multipolePayload step)).totalPotential =
      step.nextState.totalPotential +
        (input.m2lCoeffs (input.multipolePayload step)).getD 0 0 := by
  exact multipoleUpdate_addsLeadingM2LHead (step?_multipoleUpdate _hstep _hbranch)

/-- One executable FMM update after extracting a structural step. The payload is
  hidden behind the branch-specific update relation. -/
inductive FmmExecution (input : FmmInput) (state : FmmEvalState) :
  FmmStep → FmmEvalState → Prop where
  | directSum {step : FmmStep} {payload : DirectSumPayload} {updatedState : FmmEvalState} :
    FmmDirectSumUpdate input state step payload updatedState →
    FmmExecution input state step updatedState
  | multipole {step : FmmStep} {payload : MultipolePayload} {updatedState : FmmEvalState} :
    FmmMultipoleUpdate input state step payload updatedState →
    FmmExecution input state step updatedState

/-- Observable change in `totalPotential` contributed by one executable FMM step. -/
inductive FmmExecutionObserves (input : FmmInput) (state : FmmEvalState) :
    FmmStep → FmmEvalState → Potential → Prop where
  | directSum {step : FmmStep} {payload : DirectSumPayload} {updatedState : FmmEvalState} :
      FmmDirectSumUpdate input state step payload updatedState →
      FmmExecutionObserves input state step updatedState payload.totalContribution
  | multipole {step : FmmStep} {payload : MultipolePayload} {updatedState : FmmEvalState} :
      FmmMultipoleUpdate input state step payload updatedState →
      FmmExecutionObserves input state step updatedState ((input.m2lCoeffs payload).getD 0 0)

theorem step?_execution
  {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
  (hstep : input.step? state = some step) :
  ∃ updatedState, FmmExecution input state step updatedState := by
  cases hbranch : step.kernelBranch with
  | directSum =>
    refine ⟨step.nextState.applyDirectSum (input.directSumPayload step), ?_⟩
    exact .directSum (step?_directSumUpdate hstep hbranch)
  | multipole =>
    refine ⟨step.nextState.applyMultipole (input.multipolePayload step), ?_⟩
    exact .multipole (step?_multipoleUpdate hstep hbranch)

theorem execution_wellFormed
  {input : FmmInput} {state updatedState : FmmEvalState} {step : FmmStep}
  (hstate : FmmEvalState.WellFormed input state)
  (hexec : FmmExecution input state step updatedState) :
  FmmEvalState.WellFormed input updatedState := by
  cases hexec with
  | directSum hupdate =>
    exact directSumUpdate_wellFormed hstate hupdate
  | multipole hupdate =>
    exact multipoleUpdate_wellFormed hstate hupdate

theorem execution_observesIncrement
  {input : FmmInput} {state updatedState : FmmEvalState} {step : FmmStep}
  (hexec : FmmExecution input state step updatedState) :
  ∃ delta, FmmExecutionObserves input state step updatedState delta := by
  cases hexec with
  | directSum hupdate =>
    exact ⟨_, .directSum hupdate⟩
  | multipole hupdate =>
    exact ⟨_, .multipole hupdate⟩

theorem executionObservation_totalPotential
  {input : FmmInput} {state updatedState : FmmEvalState} {step : FmmStep} {delta : Potential}
  (hobs : FmmExecutionObserves input state step updatedState delta) :
  updatedState.totalPotential = step.nextState.totalPotential + delta := by
  cases hobs with
  | directSum hupdate =>
    exact directSumUpdate_totalPotential hupdate
  | multipole hupdate =>
    exact multipoleUpdate_addsLeadingM2LHead hupdate

theorem step?_execution_observesTotalPotential
  {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
  (hstep : input.step? state = some step) :
  ∃ updatedState delta,
    FmmExecution input state step updatedState ∧
    FmmExecutionObserves input state step updatedState delta ∧
    updatedState.totalPotential = step.nextState.totalPotential + delta := by
  rcases step?_execution hstep with ⟨updatedState, hexec⟩
  rcases execution_observesIncrement hexec with ⟨delta, hobs⟩
  exact ⟨updatedState, delta, hexec, hobs, executionObservation_totalPotential hobs⟩

/-- Branch-specific semantic shell for one successful FMM step.
    Near-field steps expose a direct-sum branch, while far-field steps expose a multipole branch. -/
inductive FmmTransition (input : FmmInput) (state : FmmEvalState) : FmmStep → Prop where
  | directSum {step : FmmStep} :
      input.step? state = some step →
      step.kernelBranch = .directSum →
      step.distance < input.config.admissibilityRadius →
      FmmTransition input state step
  | multipole {step : FmmStep} :
      input.step? state = some step →
      step.kernelBranch = .multipole →
      input.config.admissibilityRadius ≤ step.distance →
      FmmTransition input state step

theorem step?_transition
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstep : input.step? state = some step) :
    FmmTransition input state step := by
  by_cases hnear : input.isNearField step.cell
  · apply FmmTransition.directSum hstep
    · exact (step?_kernelBranch_eq_directSum_iff hstep).2 hnear
    · have hdist : input.cellDistance step.cell < input.config.admissibilityRadius := by
        simpa [FmmInput.isNearField] using hnear
      rw [step?_distance_eq hstep]
      exact hdist
  · apply FmmTransition.multipole hstep
    · exact (step?_kernelBranch_eq_multipole_iff hstep).2 hnear
    · have hfar : input.config.admissibilityRadius ≤ input.cellDistance step.cell := by
        have hnot : ¬ input.cellDistance step.cell < input.config.admissibilityRadius := by
          simpa [FmmInput.isNearField] using hnear
        exact le_of_not_gt hnot
      rw [step?_distance_eq hstep]
      exact hfar

theorem transition_nextState_wellFormed
    {input : FmmInput} {state : FmmEvalState} {step : FmmStep}
    (hstate : FmmEvalState.WellFormed input state)
    (htrans : FmmTransition input state step) :
    FmmEvalState.WellFormed input step.nextState := by
  cases htrans with
  | directSum hstep _ _ =>
      exact step?_nextState_wellFormed hstate hstep
  | multipole hstep _ _ =>
      exact step?_nextState_wellFormed hstate hstep

/-- Initial state: every hierarchy level is pending, and no potential has been accumulated. -/
def initialState (input : FmmInput) : FmmEvalState :=
  { pendingLevels := List.range input.hierarchy.length
    frontierMode := input.config.frontierMode
    golayWeight := input.config.golayWeight }

@[simp]
theorem initialState_frontierMode (input : FmmInput) :
    (initialState input).frontierMode = input.config.frontierMode := by
  rfl

@[simp]
theorem initialState_golayWeight (input : FmmInput) :
    (initialState input).golayWeight = input.config.golayWeight := by
  rfl

@[simp]
theorem mem_initialState_pendingLevels (input : FmmInput) (level : ℕ) :
    level ∈ (initialState input).pendingLevels ↔ level < input.hierarchy.length := by
  simp [initialState]

theorem initialState_wellFormed (input : FmmInput) :
    FmmEvalState.WellFormed input (initialState input) := by
  constructor
  · rfl
  constructor
  · rfl
  constructor
  · intro level hlevel
    simpa [initialState] using List.mem_range.mp hlevel
  · intro level hlevel
    simp [initialState] at hlevel

noncomputable def smallOracleInput : FmmInput :=
  { grid := [1, 2]
    hierarchy := [{ sourceIndices := [0] }]
    sources := [0]
    charges := [1, 0]
    targetIdx := 1
    config :=
      { order := 1
        admissibilityRadius := (1 : ℝ) / 2
        golayWeight := .w0 } }

def smallOracleStep : FmmStep :=
  { level := 0
    cell := { sourceIndices := [0] }
    center := 1
    distance := 1
    interactionKind := .farField
    nextState :=
      { pendingLevels := []
        currentLevel? := some 0
        totalPotential := 0
        frontierMode := .stack
        golayWeight := .w0 } }

noncomputable def smallOraclePayload : MultipolePayload :=
  smallOracleInput.multipolePayload smallOracleStep

noncomputable def smallOracleUpdatedState : FmmEvalState :=
  smallOracleStep.nextState.applyMultipole smallOraclePayload

@[simp]
theorem smallOracleInput_targetPos :
    smallOracleInput.targetPos = 2 := by
  simp [smallOracleInput, FmmInput.targetPos]

@[simp]
theorem smallOraclePayload_multipoleCoeffs :
    smallOraclePayload.multipoleCoeffs = [1] := by
  norm_num [smallOraclePayload, smallOracleInput, smallOracleStep,
    FmmInput.targetPos, FmmInput.multipolePayload, FmmInput.p2mCoeffs,
    FmmInput.m2lCoeffs, FmmInput.chargeAt]

@[simp]
theorem smallOraclePayload_localCoeffs :
    smallOraclePayload.localCoeffs = [1] := by
  norm_num [smallOraclePayload, smallOracleInput, smallOracleStep,
    FmmInput.targetPos, FmmInput.multipolePayload, FmmInput.p2mCoeffs,
    FmmInput.m2lCoeffs, FmmInput.chargeAt]

@[simp]
theorem smallOraclePayload_leadingLocalCoeff :
    smallOraclePayload.leadingLocalCoeff = 1 := by
  norm_num [smallOraclePayload, smallOracleInput, smallOracleStep,
    FmmInput.targetPos, MultipolePayload.leadingLocalCoeff,
    FmmInput.multipolePayload, FmmInput.p2mCoeffs, FmmInput.m2lCoeffs,
    FmmInput.chargeAt]

@[simp]
theorem smallOracle_applyMultipole_totalPotential :
    (smallOracleStep.nextState.applyMultipole smallOraclePayload).totalPotential = 1 := by
  norm_num [smallOraclePayload, smallOracleInput, smallOracleStep,
    FmmInput.targetPos, FmmEvalState.applyMultipole,
    MultipolePayload.leadingLocalCoeff, FmmInput.multipolePayload,
    FmmInput.p2mCoeffs, FmmInput.m2lCoeffs, FmmInput.chargeAt]

@[simp]
theorem smallOracleStep_kernelBranch :
    smallOracleStep.kernelBranch = .multipole := by
  simp [smallOracleStep, FmmStep.kernelBranch, InteractionKind.toKernelBranch]

@[simp]
theorem smallOracle_step? :
    smallOracleInput.step? (initialState smallOracleInput) = some smallOracleStep := by
  norm_num [smallOracleInput, smallOracleStep, initialState,
    FmmConfig.frontierMode, FrontierMode.ofGolayWeight, FrontierMode.ofTau, GolayWeight.toNat,
    FmmInput.step?, FmmEvalState.popLevel, FmmInput.cellAt?, FmmHierarchy.cellAt?,
    FmmInput.targetPos, FmmInput.cellCenter, FmmInput.cellDistance,
    FmmInput.interactionKind, FmmInput.isNearField]

theorem smallOracle_execution :
    FmmExecution smallOracleInput (initialState smallOracleInput) smallOracleStep smallOracleUpdatedState := by
  simpa [smallOracleUpdatedState, smallOraclePayload] using
    (FmmExecution.multipole (step?_multipoleUpdate smallOracle_step? smallOracleStep_kernelBranch) :
      FmmExecution smallOracleInput (initialState smallOracleInput) smallOracleStep
        (smallOracleStep.nextState.applyMultipole (smallOracleInput.multipolePayload smallOracleStep)))

theorem smallOracle_execution_totalPotential :
    smallOracleUpdatedState.totalPotential = 1 := by
  simpa [smallOracleUpdatedState] using smallOracle_applyMultipole_totalPotential

theorem smallOracle_execution_observesTotalPotential :
    ∃ delta,
      FmmExecutionObserves smallOracleInput (initialState smallOracleInput)
        smallOracleStep smallOracleUpdatedState delta ∧
      smallOracleUpdatedState.totalPotential = smallOracleStep.nextState.totalPotential + delta := by
  rcases execution_observesIncrement smallOracle_execution with ⟨delta, hobs⟩
  refine ⟨delta, hobs, ?_⟩
  exact executionObservation_totalPotential hobs

/-- CI gate for the minimal far-field oracle: the first executable step exists,
    observes a concrete increment, and reaches the expected total potential. -/
theorem smallOracle_ci_gate :
    ∃ delta,
      FmmExecution smallOracleInput (initialState smallOracleInput)
        smallOracleStep smallOracleUpdatedState ∧
      FmmExecutionObserves smallOracleInput (initialState smallOracleInput)
        smallOracleStep smallOracleUpdatedState delta ∧
      smallOracleUpdatedState.totalPotential = smallOracleStep.nextState.totalPotential + delta ∧
      smallOracleUpdatedState.totalPotential = 1 := by
  rcases smallOracle_execution_observesTotalPotential with ⟨delta, hobs, htotal⟩
  refine ⟨delta, smallOracle_execution, hobs, htotal, ?_⟩
  exact smallOracle_execution_totalPotential

end HatsuYakitori.Fmm
