;;;; kak_decomposition.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'kak_decomposition
      'kak_decomposition
      (scheme#list)
      '((K-frontier . kak_decomposition#K-frontier)
        (K-push . kak_decomposition#K-push)
        (K-pop . kak_decomposition#K-pop)
        (K-empty? . kak_decomposition#K-empty?)
        (K-size . kak_decomposition#K-size)
        (relax-bound . kak_decomposition#relax-bound)
        (graph-neighbors . kak_decomposition#graph-neighbors)
        (KAK-apply . kak_decomposition#KAK-apply)
        (KAK-apply-golay . kak_decomposition#KAK-apply-golay)
        (+INF+ . kak_decomposition#+INF+))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
