const std = @import("std");

/// # Terrabin Space Provider (SQL Generator Prototype)
///
/// This module parses a category-theoretic structure (BSD Quiver) that has been
/// formally proven in Lean, and automatically generates the schema and logic
/// for a "database computation space" that runs on RDB (SQLite).
///
/// The biggest feature of this generator is that it evaluates algebraic
/// functions such as `combineEffects` and expands all possible composition
/// patterns of side effects into SQL tables.
///
/// This code is written with modern Zig idioms in mind (based on the official
/// Zig documentation for Values: enums, structs, array literals, and compile-time
/// evaluation). It is intended to be used together with **tinyzimmer/sqlc-gen-zig**,
/// a community plugin for sqlc that generates Zig code from SQL schema + queries.
/// You would typically keep the generated SQL in `schema.sql` / `queries.sql`
/// and let sqlc produce type-safe Zig wrappers around the tables/queries defined here.

/// Geometric modality spatial tag (MachineConstants.lean: SpaceTag)
pub const SpaceTag = enum {
    affine,
    banach,
    hybrid,
};

/// Classification of transformation effects / side effects (BSDQuiver.lean: TransformEffect)
pub const TransformEffect = enum {
    preserves_algebraic,
    adds_topology,
    forgets_topology,
    mixes_structures,
};

/// Composition rules for transformation effects (XZ involution / identity rules)
/// Direct port of Lean's `combineEffects` function to Zig.
/// This function is evaluated at compile-time or runtime to generate
/// the SQL mapping table.
pub fn combineEffects(l: TransformEffect, r: TransformEffect) TransformEffect {
    if (l == .preserves_algebraic) return r;
    if (r == .preserves_algebraic) return l;
    if (l == .adds_topology and r == .forgets_topology) return .preserves_algebraic; // XZ = I
    if (l == .forgets_topology and r == .adds_topology) return .preserves_algebraic; // ZX = I
    return .mixes_structures;
}

/// Structure representing Golay weight and Galois height
pub const GolayWeight = struct {
    tau: u8,
    height: f64,
    tag: SpaceTag,
};

/// Hardcoded Golay weight constants (initial seed data)
/// Using modern Zig array literal syntax with inferred length [_].
pub const golay_weights = [_]GolayWeight{
    .{ .tau = 0, .height = 0.0, .tag = .affine },
    .{ .tau = 8, .height = 2.666667, .tag = .banach },
    .{ .tau = 12, .height = 4.0, .tag = .hybrid },
    .{ .tau = 16, .height = 5.333333, .tag = .banach },
    .{ .tau = 24, .height = 8.0, .tag = .banach },
};

/// BSD Quiver arrow (transition) definition
pub const BSDArrow = struct {
    id: []const u8,
    source: []const u8,
    target: []const u8,
    effect: TransformEffect,
};

pub const bsd_arrows = [_]BSDArrow{
    .{ .id = "tensor_bang", .source = "leech", .target = "affine_dual", .effect = .mixes_structures },
    .{ .id = "oplus_padic", .source = "affine_dual", .target = "padic", .effect = .adds_topology },
    .{ .id = "project_selmer", .source = "leech", .target = "selmer", .effect = .preserves_algebraic },
    .{ .id = "recover", .source = "selmer", .target = "affine_dual", .effect = .mixes_structures },
};

/// Outputs SQLite DDL (table definitions)
/// This SQL can be placed in a `schema.sql` file for sqlc (with tinyzimmer/sqlc-gen-zig)
/// to generate type-safe Zig models and query functions.
pub fn generateSchema(writer: anytype) !void {
    try writer.writeAll(
        \\-- ==========================================================
        \\-- 1. Schema Definition (Auto-generated by Zig)
        \\-- ==========================================================
        \\CREATE TABLE space_tags (tag_id TEXT PRIMARY KEY);
        \\CREATE TABLE transform_effects (effect_id TEXT PRIMARY KEY);
        \\
        \\CREATE TABLE golay_weights (
        \\    tau_value INTEGER PRIMARY KEY,
        \\    galois_height REAL,
        \\    space_tag TEXT REFERENCES space_tags(tag_id)
        \\);
        \\
        \\CREATE TABLE effect_composition_rules (
        \\    left_effect TEXT REFERENCES transform_effects(effect_id),
        \\    right_effect TEXT REFERENCES transform_effects(effect_id),
        \\    result_effect TEXT REFERENCES transform_effects(effect_id),
        \\    PRIMARY KEY (left_effect, right_effect)
        \\);
        \\
        \\CREATE TABLE bsd_arrows (
        \\    arrow_id TEXT PRIMARY KEY,
        \\    source_vertex TEXT,
        \\    target_vertex TEXT,
        \\    arrow_effect TEXT REFERENCES transform_effects(effect_id)
        \\);
        \\
        \\
    );
}

/// Outputs master data and computed logic as INSERT statements
/// These INSERTs can be placed in a separate seed file or combined with schema.sql.
/// sqlc will then generate Zig structs and query functions for interacting with this data.
pub fn generateData(writer: anytype) !void {
    try writer.writeAll("-- ==========================================================\n");
    try writer.writeAll("-- 2. Logic & Seed Data Insertion\n");
    try writer.writeAll("-- ==========================================================\n");

    // Automatically generate master data for tags and effects from enums
    // (using std.enums.values for compile-time iteration)
    for (std.enums.values(SpaceTag)) |tag| {
        try writer.print("INSERT INTO space_tags VALUES ('{s}');\n", .{@tagName(tag)});
    }
    for (std.enums.values(TransformEffect)) |effect| {
        try writer.print("INSERT INTO transform_effects VALUES ('{s}');\n", .{@tagName(effect)});
    }

    try writer.writeAll("\n-- Golay Weights\n");
    for (golay_weights) |w| {
        try writer.print("INSERT INTO golay_weights VALUES ({d}, {d:.6}, '{s}');\n", .{
            w.tau,
            w.height,
            @tagName(w.tag),
        });
    }

    try writer.writeAll("\n-- Effect Composition Rules\n");
    // [Important] Evaluate all combinations on the Zig side (comptime-friendly)
    // and convert the table to SQL. This demonstrates Zig's strength in compile-time computation.
    const effects = std.enums.values(TransformEffect);
    for (effects) |l| {
        for (effects) |r| {
            const res = combineEffects(l, r);
            try writer.print("INSERT INTO effect_composition_rules VALUES ('{s}', '{s}', '{s}');\n", .{
                @tagName(l),
                @tagName(r),
                @tagName(res),
            });
        }
    }

    try writer.writeAll("\n-- BSD Arrows\n");
    for (bsd_arrows) |a| {
        try writer.print("INSERT INTO bsd_arrows VALUES ('{s}', '{s}', '{s}', '{s}');\n", .{
            a.id,
            a.source,
            a.target,
            @tagName(a.effect),
        });
    }
}

/// Outputs a recursive CTE (dynamic programming) computation query
/// This query can be placed in `queries.sql` so that sqlc-gen-zig generates
/// a type-safe Zig function to execute the path computation over the BSD quiver.
pub fn generateComputationQuery(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\-- ==========================================================
        \\-- 3. Recursive Computation Space Query
        \\-- ==========================================================
        \\WITH RECURSIVE bsd_paths AS (
        \\    SELECT
        \\        'leech' AS current_vertex,
        \\        0 AS path_length,
        \\        'preserves_algebraic' AS accumulated_effect,
        \\        'leech' AS path_history
        \\    UNION ALL
        \\    SELECT
        \\        a.target_vertex AS current_vertex,
        \\        p.path_length + 1 AS path_length,
        \\        comp.result_effect AS accumulated_effect,
        \\        p.path_history || ' -> ' || a.target_vertex AS path_history
        \\    FROM bsd_paths p
        \\    JOIN bsd_arrows a ON p.current_vertex = a.source_vertex
        \\    JOIN effect_composition_rules comp
        \\        ON p.accumulated_effect = comp.left_effect
        \\        AND a.arrow_effect = comp.right_effect
        \\    WHERE p.path_length < 5
        \\)
        \\SELECT path_history, path_length, accumulated_effect
        \\FROM bsd_paths
        \\ORDER BY path_length;
        \\
    );
}

/// Compiler entry point (for standalone SQL generation)
/// When using with sqlc, you typically won't call main(); instead, the SQL output
/// from these functions goes into your schema/queries files for sqlc to process.
pub fn main() !void {
    const stdout_file = std.io.getStdOut().writer();
    var bw = std.io.bufferedWriter(stdout_file);
    const writer = bw.writer();

    try generateSchema(writer);
    try generateData(writer);
    try generateComputationQuery(writer);

    try bw.flush();
}
